#include <stdio.h>
#include "srcs/ft_printf.h"

int		main(void)
{
	ft_printf("--------------------%%x--------------------\n");
	printf("01) Vrai PRINTF : |%x|\n", 34);
	ft_printf("01) Mon PRINTF  : |%x|\n", 34);
	printf("02) Vrai PRINTF : |%x|\n", -34);
	ft_printf("02) Mon PRINTF  : |%x|\n", -34);
	printf("03) Vrai PRINTF : |%-x|\n", 50);
	ft_printf("03) Mon PRINTF  : |%-x|\n", 50);
	printf("04) Vrai PRINTF : |%10x|\n", 90);
	ft_printf("04) Mon PRINTF  : |%10x|\n", 90);
	printf("05) Vrai PRINTF : |%.10x|\n", 90);
	ft_printf("05) Mon PRINTF  : |%.10x|\n", 90);
	printf("06) Vrai PRINTF : |%15x|\n", -100);
	ft_printf("06) Mon PRINTF  : |%15x|\n", -100);
	printf("07) Vrai PRINTF : |%.15x|\n", -100);
	ft_printf("07) Mon PRINTF  : |%.15x|\n", -100);
	printf("08) Vrai PRINTF : |%10.5x|\n", 52);
	ft_printf("08) Mon PRINTF  : |%10.5x|\n", 52);
	printf("09) Vrai PRINTF : |%5.10x|\n", 52);
	ft_printf("09) Mon PRINTF  : |%5.10x|\n", 52);
	printf("10) Vrai PRINTF : |%20.15x|\n", -100000);
	ft_printf("10) Mon PRINTF  : |%20.15x|\n", -100000);
	printf("11) Vrai PRINTF : |%15.20x|\n", -100000);
	ft_printf("11) Mon PRINTF  : |%15.20x|\n", -100000);
	printf("12) Vrai PRINTF : |%-10x|\n", 144);
	ft_printf("12) Mon PRINTF  : |%-10x|\n", 144);
	printf("13) Vrai PRINTF : |%-.10x|\n", 144);
	ft_printf("13) Mon PRINTF  : |%-.10x|\n", 144);
	printf("14) Vrai PRINTF : |%-20x|\n", -20000000);
	ft_printf("14) Mon PRINTF  : |%-20x|\n", -20000000);
	printf("15) Vrai PRINTF : |%08x|\n", 64);
	ft_printf("15) Mon PRINTF  : |%08x|\n", 64);
	printf("16) Vrai PRINTF : |%03.4x|\n", 10);
	ft_printf("16) Mon PRINTF  : |%03.4x|\n", 10);
	printf("17) Vrai PRINTF : |%#x|\n", 34);
	ft_printf("17) Mon PRINTF  : |%#x|\n", 34);
	printf("18) Vrai PRINTF : |%#.5x|\n", 34);
	ft_printf("18) Mon PRINTF  : |%#.5x|\n", 34);
	printf("19) Vrai PRINTF : |%#5x|\n", 86);
	ft_printf("19) Mon PRINTF  : |%#5x|\n", 86);
	printf("20) Vrai PRINTF : |%#10.5x|\n", 70);
	ft_printf("20) Mon PRINTF  : |%#10.5x|\n", 70);
	printf("21) Vrai PRINTF : |%#x|\n", 0);
	ft_printf("21) Mon PRINTF  : |%#x|\n", 0);
	printf("22) Vrai PRINTF : |%#.x|\n", 0);
	ft_printf("22) Mon PRINTF  : |%#.x|\n", 0);
	printf("23) Vrai PRINTF : |%.x|\n", 0);
	ft_printf("23) Mon PRINTF  : |%.x|\n", 0);
	printf("24) Vrai PRINTF : |%.x|\n", 88);
	ft_printf("24) Mon PRINTF  : |%.x|\n", 88);
	printf("25) Vrai PRINTF : |%#.x|\n", 88);
	ft_printf("25) Mon PRINTF  : |%#.x|\n", 88);
	printf("26) Vrai PRINTF : |%x|\n", UINT_MAX);
	ft_printf("26) Mon PRINT   : |%x|\n", UINT_MAX);
	printf("27) Vrai PRINTF : |%#x|\n", UINT_MAX);
	ft_printf("27) Mon PRINTF  : |%#x|\n", UINT_MAX);
	printf("28) Vrai PRINTF : |%#x| |%#x|\n", (unsigned int)-1, UINT_MAX + 1);
	ft_printf("28) Mon PRINTF  : |%#x| |%#x|\n", (unsigned int)-1, UINT_MAX + 1);
	printf("29) Vrai PRINTF : |%x| |%x|\n", (unsigned int)-1, UINT_MAX + 1);
	ft_printf("29) Mon PRINTF  : |%x| |%x|\n", (unsigned int)-1, UINT_MAX + 1);
	printf("30) Vrai PRINTF : |%x| |%x| |%x| |%x| |%x| |%x|\n", 42, 100, 25, 16, 30, 69);
	ft_printf("30) Mon PRINTF  : |%x| |%x| |%x| |%x| |%x| |%x|\n", 42, 100, 25, 16, 30, 69);
	printf("31) Vrai PRINTF : |%10x| |%-10x| |%.5x| |%-.5x| |%-x|\n", 42, 100, 25, 16, 30);
	ft_printf("31) Mon PRINTF  : |%10x| |%-10x| |%.5x| |%-.5x| |%-x|\n", 42, 100, 25, 16, 30);
	printf("32) Vrai PRINTF : |%x| |%x| |%x| |%x| |%x| |%x|\n", -42, -100, -25, -16, -30, -69);
	ft_printf("32) Mon PRINTF  : |%x| |%x| |%x| |%x| |%x| |%x|\n", -42, -100, -25, -16, -30, -69);
	printf("33) Vrai PRINTF : |%10x| |%-10x| |%.5x| |%-.5x| |%-x|\n", -42, -100, -25, -16, -30);
	ft_printf("33) Mon PRINTF  : |%10x| |%-10x| |%.5x| |%-.5x| |%-x|\n", -42, -100, -25, -16, -30);
	ft_printf("--------------------%%hx--------------------\n");
	printf("01) Vrai PRINTF : |%hx|\n", (unsigned short)34);
	ft_printf("01) Mon PRINTF  : |%hx|\n", (unsigned short)34);
	printf("02) Vrai PRINTF : |%hx|\n", (unsigned short)-34);
	ft_printf("02) Mon PRINTF  : |%hx|\n", (unsigned short)-34);
	printf("03) Vrai PRINTF : |%-hx|\n", (unsigned short)50);
	ft_printf("03) Mon PRINTF  : |%-hx|\n", (unsigned short)50);
	printf("04) Vrai PRINTF : |%10hx|\n", (unsigned short)90);
	ft_printf("04) Mon PRINTF  : |%10hx|\n", (unsigned short)90);
	printf("05) Vrai PRINTF : |%.10hx|\n", (unsigned short)90);
	ft_printf("05) Mon PRINTF  : |%.10hx|\n", (unsigned short)90);
	printf("06) Vrai PRINTF : |%15hx|\n", (unsigned short)-100);
	ft_printf("06) Mon PRINTF  : |%15hx|\n", (unsigned short)-100);
	printf("07) Vrai PRINTF : |%.15hx|\n", (unsigned short)-100);
	ft_printf("07) Mon PRINTF  : |%.15hx|\n", (unsigned short)-100);
	printf("08) Vrai PRINTF : |%10.5hx|\n", (unsigned short)52);
	ft_printf("08) Mon PRINTF  : |%10.5hx|\n", (unsigned short)52);
	printf("09) Vrai PRINTF : |%5.10hx|\n", (unsigned short)52);
	ft_printf("09) Mon PRINTF  : |%5.10hx|\n", (unsigned short)52);
	printf("10) Vrai PRINTF : |%20.15hx|\n", (unsigned short)-10000);
	ft_printf("10) Mon PRINTF  : |%20.15hx|\n", (unsigned short)-10000);
	printf("11) Vrai PRINTF : |%15.20hx|\n", (unsigned short)-10000);
	ft_printf("11) Mon PRINTF  : |%15.20hx|\n", (unsigned short)-10000);
	printf("12) Vrai PRINTF : |%-10hx|\n", (unsigned short)144);
	ft_printf("12) Mon PRINTF  : |%-10hx|\n", (unsigned short)144);
	printf("13) Vrai PRINTF : |%-.10hx|\n", (unsigned short)144);
	ft_printf("13) Mon PRINTF  : |%-.10hx|\n", (unsigned short)144);
	printf("14) Vrai PRINTF : |%-20hx|\n", (unsigned short)-20000);
	ft_printf("14) Mon PRINTF  : |%-20hx|\n", (unsigned short)-20000);
	printf("15) Vrai PRINTF : |%08hx|\n", (unsigned short)64);
	ft_printf("15) Mon PRINTF  : |%08hx|\n", (unsigned short)64);
	printf("16) Vrai PRINTF : |%03.4hx|\n", (unsigned short)10);
	ft_printf("16) Mon PRINTF  : |%03.4hx|\n", (unsigned short)10);
	printf("17) Vrai PRINTF : |%#hx|\n", (unsigned short)34);
	ft_printf("17) Mon PRINTF  : |%#hx|\n", (unsigned short)34);
	printf("18) Vrai PRINTF : |%#.5hx|\n", (unsigned short)34);
	ft_printf("18) Mon PRINTF  : |%#.5hx|\n", (unsigned short)34);
	printf("19) Vrai PRINTF : |%#5hx|\n", (unsigned short)86);
	ft_printf("19) Mon PRINTF  : |%#5hx|\n", (unsigned short)86);
	printf("20) Vrai PRINTF : |%#10.5hx|\n", (unsigned short)70);
	ft_printf("20) Mon PRINTF  : |%#10.5hx|\n", (unsigned short)70);
	printf("21) Vrai PRINTF : |%#hx|\n", (unsigned short)0);
	ft_printf("21) Mon PRINTF  : |%#hx|\n", (unsigned short)0);
	printf("22) Vrai PRINTF : |%#.hx|\n", (unsigned short)0);
	ft_printf("22) Mon PRINTF  : |%#.hx|\n", (unsigned short)0);
	printf("23) Vrai PRINTF : |%.hx|\n", (unsigned short)0);
	ft_printf("23) Mon PRINTF  : |%.hx|\n", (unsigned short)0);
	printf("24) Vrai PRINTF : |%.hx|\n", (unsigned short)88);
	ft_printf("24) Mon PRINTF  : |%.hx|\n", (unsigned short)88);
	printf("25) Vrai PRINTF : |%#.hx|\n", (unsigned short)88);
	ft_printf("25) Mon PRINTF  : |%#.hx|\n", (unsigned short)88);
	printf("26) Vrai PRINTF : |%hx|\n", (unsigned short)USHRT_MAX);
	ft_printf("26) Mon PRINTF  : |%hx|\n", (unsigned short)USHRT_MAX);
	printf("27) Vrai PRINTF : |%#hx|\n", (unsigned short)USHRT_MAX);
	ft_printf("27) Mon PRINTF  : |%#hx|\n", (unsigned short)USHRT_MAX);
	printf("28) Vrai PRINTF : |%#hx| |%#hx|\n", (unsigned short)-1, (unsigned short)65536);
	ft_printf("28) Mon PRINTF  : |%#hx| |%#hx|\n", (unsigned short)-1, (unsigned short)65536);
	ft_printf("--------------------%%hhx--------------------\n");
	printf("01) Vrai PRINTF : |%hhx|\n", (unsigned char)34);
	ft_printf("01) Mon PRINTF  : |%hhx|\n", (unsigned char)34);
	printf("02) Vrai PRINTF : |%hhx|\n", (unsigned char)-34);
	ft_printf("02) Mon PRINTF  : |%hhx|\n", (unsigned char)-34);
	printf("03) Vrai PRINTF : |%-hhx|\n", (unsigned char)50);
	ft_printf("03) Mon PRINTF  : |%-hhx|\n", (unsigned char)50);
	printf("04) Vrai PRINTF : |%10hhx|\n", (unsigned char)90);
	ft_printf("04) Mon PRINTF  : |%10hhx|\n", (unsigned char)90);
	printf("05) Vrai PRINTF : |%.10hhx|\n", (unsigned char)90);
	ft_printf("05) Mon PRINTF  : |%.10hhx|\n", (unsigned char)90);
	printf("06) Vrai PRINTF : |%15hhx|\n", (unsigned char)-100);
	ft_printf("06) Mon PRINTF  : |%15hhx|\n", (unsigned char)-100);
	printf("07) Vrai PRINTF : |%.15hhx|\n", (unsigned char)-100);
	ft_printf("07) Mon PRINTF  : |%.15hhx|\n", (unsigned char)-100);
	printf("08) Vrai PRINTF : |%10.5hhx|\n", (unsigned char)52);
	ft_printf("08) Mon PRINTF  : |%10.5hhx|\n", (unsigned char)52);
	printf("09) Vrai PRINTF : |%5.10hhx|\n", (unsigned char)52);
	ft_printf("09) Mon PRINTF  : |%5.10hhx|\n", (unsigned char)52);
	printf("10) Vrai PRINTF : |%20.15hhx|\n", (unsigned char)-10000);
	ft_printf("10) Mon PRINTF  : |%20.15hhx|\n", (unsigned char)-10000);
	printf("11) Vrai PRINTF : |%15.20hhx|\n", (unsigned char)-10000);
	ft_printf("11) Mon PRINTF  : |%15.20hhx|\n", (unsigned char)-10000);
	printf("12) Vrai PRINTF : |%-10hhx|\n", (unsigned char)144);
	ft_printf("12) Mon PRINTF  : |%-10hhx|\n", (unsigned char)144);
	printf("13) Vrai PRINTF : |%-.10hhx|\n", (unsigned char)144);
	ft_printf("13) Mon PRINTF  : |%-.10hhx|\n", (unsigned char)144);
	printf("14) Vrai PRINTF : |%-20hhx|\n", (unsigned char)-20000);
	ft_printf("14) Mon PRINTF  : |%-20hhx|\n", (unsigned char)-20000);
	printf("15) Vrai PRINTF : |%08hhx|\n", (unsigned char)64);
	ft_printf("15) Mon PRINTF  : |%08hhx|\n", (unsigned char)64);
	printf("16) Vrai PRINTF : |%03.4hhx|\n", (unsigned char)10);
	ft_printf("16) Mon PRINTF  : |%03.4hhx|\n", (unsigned char)10);
	printf("17) Vrai PRINTF : |%#hhx|\n", (unsigned char)34);
	ft_printf("17) Mon PRINTF  : |%#hhx|\n", (unsigned char)34);
	printf("18) Vrai PRINTF : |%#.5hhx|\n", (unsigned char)34);
	ft_printf("18) Mon PRINTF  : |%#.5hhx|\n", (unsigned char)34);
	printf("19) Vrai PRINTF : |%#5hhx|\n", (unsigned char)86);
	ft_printf("19) Mon PRINTF  : |%#5hhx|\n", (unsigned char)86);
	printf("20) Vrai PRINTF : |%#10.5hhx|\n", (unsigned char)70);
	ft_printf("20) Mon PRINTF  : |%#10.5hhx|\n", (unsigned char)70);
	printf("21) Vrai PRINTF : |%#hhx|\n", (unsigned char)0);
	ft_printf("21) Mon PRINTF  : |%#hhx|\n", (unsigned char)0);
	printf("22) Vrai PRINTF : |%#.hhx|\n", (unsigned char)0);
	ft_printf("22) Mon PRINTF  : |%#.hhx|\n", (unsigned char)0);
	printf("23) Vrai PRINTF : |%.hhx|\n", (unsigned char)0);
	ft_printf("23) Mon PRINTF  : |%.hhx|\n", (unsigned char)0);
	printf("24) Vrai PRINTF : |%.hhx|\n", (unsigned char)88);
	ft_printf("24) Mon PRINTF  : |%.hhx|\n", (unsigned char)88);
	printf("25) Vrai PRINTF : |%#.hhx|\n", (unsigned char)88);
	ft_printf("25) Mon PRINTF  : |%#.hhx|\n", (unsigned char)88);
	printf("26) Vrai PRINTF : |%hhx|\n", (unsigned char)255);
	ft_printf("26) Mon PRINTF  : |%hhx|\n", (unsigned char)255);
	printf("27) Vrai PRINTF : |%#hhx|\n", (unsigned char)255);
	ft_printf("27) Mon PRINTF  : |%#hhx|\n", (unsigned char)255);
	printf("28) Vrai PRINTF : |%#hhx| |%#hhx|\n", (unsigned char)-1, (unsigned char)256);
	ft_printf("28) Mon PRINTF  : |%#hhx| |%#hhx|\n", (unsigned char)-1, (unsigned char) 256);
	ft_printf("--------------------%%lx--------------------\n");
	printf("01) Vrai PRINTF : |%lx|\n",(unsigned long)34);
	ft_printf("01) Mon PRINTF  : |%lx|\n", (unsigned long)34);
	printf("02) Vrai PRINTF : |%lx|\n", (unsigned long)-34);
	ft_printf("02) Mon PRINTF  : |%lx|\n", (unsigned long)-34);
	printf("03) Vrai PRINTF : |%-lx|\n", (unsigned long)50);
	ft_printf("03) Mon PRINTF  : |%-lx|\n", (unsigned long)50);
	printf("04) Vrai PRINTF : |%10lx|\n", (unsigned long)90);
	ft_printf("04) Mon PRINTF  : |%10lx|\n", (unsigned long)90);
	printf("05) Vrai PRINTF : |%.10lx|\n", (unsigned long)90);
	ft_printf("05) Mon PRINTF  : |%.10lx|\n", (unsigned long)90);
	printf("06) Vrai PRINTF : |%15lx|\n", (unsigned long)-100);
	ft_printf("06) Mon PRINTF  : |%15lx|\n", (unsigned long)-100);
	printf("07) Vrai PRINTF : |%.15lx|\n", (unsigned long)-100);
	ft_printf("07) Mon PRINTF  : |%.15lx|\n", (unsigned long)-100);
	printf("08) Vrai PRINTF : |%10.5lx|\n", (unsigned long)52);
	ft_printf("08) Mon PRINTF  : |%10.5lx|\n", (unsigned long)52);
	printf("09) Vrai PRINTF : |%5.10lx|\n", (unsigned long)52);
	ft_printf("09) Mon PRINTF  : |%5.10lx|\n", (unsigned long)52);
	printf("10) Vrai PRINTF : |%20.15lx|\n", (unsigned long)-100000);
	ft_printf("10) Mon PRINTF  : |%20.15lx|\n", (unsigned long)-100000);
	printf("11) Vrai PRINTF : |%15.20lx|\n", (unsigned long)-100000);
	ft_printf("11) Mon PRINTF  : |%15.20lx|\n", (unsigned long)-100000);
	printf("12) Vrai PRINTF : |%-10lx|\n", (unsigned long)144);
	ft_printf("12) Mon PRINTF  : |%-10lx|\n", (unsigned long)144);
	printf("13) Vrai PRINTF : |%-.10lx|\n", (unsigned long)144);
	ft_printf("13) Mon PRINTF  : |%-.10lx|\n", (unsigned long)144);
	printf("14) Vrai PRINTF : |%-20lx|\n", (unsigned long)-20000000);
	ft_printf("14) Mon PRINTF  : |%-20lx|\n", (unsigned long)-20000000);
	printf("15) Vrai PRINTF : |%08lx|\n", (unsigned long)64);
	ft_printf("15) Mon PRINTF  : |%08lx|\n", (unsigned long)64);
	printf("16) Vrai PRINTF : |%03.4lx|\n", (unsigned long)10);
	ft_printf("16) Mon PRINTF  : |%03.4lx|\n", (unsigned long)10);
	printf("17) Vrai PRINTF : |%#lx|\n", (unsigned long)34);
	ft_printf("17) Mon PRINTF  : |%#lx|\n", (unsigned long)34);
	printf("18) Vrai PRINTF : |%#.5lx|\n", (unsigned long)34);
	ft_printf("18) Mon PRINTF  : |%#.5lx|\n", (unsigned long)34);
	printf("19) Vrai PRINTF : |%#5lx|\n", (unsigned long)86);
	ft_printf("19) Mon PRINTF  : |%#5lx|\n", (unsigned long)86);
	printf("20) Vrai PRINTF : |%#10.5lx|\n", (unsigned long)70);
	ft_printf("20) Mon PRINTF  : |%#10.5lx|\n", (unsigned long)70);
	printf("21) Vrai PRINTF : |%#lx|\n", (unsigned long)0);
	ft_printf("21) Mon PRINTF  : |%#lx|\n", (unsigned long)0);
	printf("22) Vrai PRINTF : |%#.lx|\n", (unsigned long)0);
	ft_printf("22) Mon PRINTF  : |%#.lx|\n", (unsigned long)0);
	printf("23) Vrai PRINTF : |%.lx|\n", (unsigned long)0);
	ft_printf("23) Mon PRINTF  : |%.lx|\n", (unsigned long)0);
	printf("24) Vrai PRINTF : |%.lx|\n", (unsigned long)88);
	ft_printf("24) Mon PRINTF  : |%.lx|\n", (unsigned long)88);
	printf("25) Vrai PRINTF : |%#.lx|\n", (unsigned long)88);
	ft_printf("25) Mon PRINTF  : |%#.lx|\n", (unsigned long)88);
	printf("26) Vrai PRINTF : |%lx|\n", (unsigned long)UINT_MAX);
	ft_printf("26) Mon PRINTF  : |%lx|\n", (unsigned long)UINT_MAX);
	printf("27) Vrai PRINTF : |%#lx|\n", (unsigned long)-1, ULONG_MAX);
	ft_printf("27) Mon PRINTF  : |%#lx|\n", (unsigned long)-1, ULONG_MAX);
	printf("28) Vrai PRINTF : |%#lx| |%#lx|\n", (unsigned long)-1, ULONG_MAX + 1);
	ft_printf("28) Mon PRINTF  : |%#lx| |%#lx|\n", (unsigned long)-1, ULONG_MAX + 1);
	ft_printf("--------------------%%llx--------------------\n");
	printf("01) Vrai PRINTF : |%llx|\n",(unsigned long long)34);
	ft_printf("01) Mon PRINTF  : |%llx|\n", (unsigned long long)34);
	printf("02) Vrai PRINTF : |%llx|\n", (unsigned long long)-34);
	ft_printf("02) Mon PRINTF  : |%llx|\n", (unsigned long long)-34);
	printf("03) Vrai PRINTF : |%-llx|\n", (unsigned long long)50);
	ft_printf("03) Mon PRINTF  : |%-llx|\n", (unsigned long long)50);
	printf("04) Vrai PRINTF : |%10llx|\n", (unsigned long long)90);
	ft_printf("04) Mon PRINTF  : |%10llx|\n", (unsigned long long)90);
	printf("05) Vrai PRINTF : |%.10llx|\n", (unsigned long long)90);
	ft_printf("05) Mon PRINTF  : |%.10llx|\n", (unsigned long long)90);
	printf("06) Vrai PRINTF : |%15llx|\n", (unsigned long long)-100);
	ft_printf("06) Mon PRINTF  : |%15llx|\n", (unsigned long long)-100);
	printf("07) Vrai PRINTF : |%.15llx|\n", (unsigned long long)-100);
	ft_printf("07) Mon PRINTF  : |%.15llx|\n", (unsigned long long)-100);
	printf("08) Vrai PRINTF : |%10.5llx|\n", (unsigned long long)52);
	ft_printf("08) Mon PRINTF  : |%10.5llx|\n", (unsigned long long)52);
	printf("09) Vrai PRINTF : |%5.10llx|\n", (unsigned long long)52);
	ft_printf("09) Mon PRINTF  : |%5.10llx|\n", (unsigned long long)52);
	printf("10) Vrai PRINTF : |%20.15llx|\n", (unsigned long long)-100000);
	ft_printf("10) Mon PRINTF  : |%20.15llx|\n", (unsigned long long)-100000);
	printf("11) Vrai PRINTF : |%15.20llx|\n", (unsigned long long)-100000);
	ft_printf("11) Mon PRINTF  : |%15.20llx|\n", (unsigned long long)-100000);
	printf("12) Vrai PRINTF : |%-10llx|\n", (unsigned long long)144);
	ft_printf("12) Mon PRINTF  : |%-10llx|\n", (unsigned long long)144);
	printf("13) Vrai PRINTF : |%-.10llx|\n", (unsigned long long)144);
	ft_printf("13) Mon PRINTF  : |%-.10llx|\n", (unsigned long long)144);
	printf("14) Vrai PRINTF : |%-20llx|\n", (unsigned long long)-20000000);
	ft_printf("14) Mon PRINTF  : |%-20llx|\n", (unsigned long long)-20000000);
	printf("15) Vrai PRINTF : |%08llx|\n", (unsigned long long)64);
	ft_printf("15) Mon PRINTF  : |%08llx|\n", (unsigned long long)64);
	printf("16) Vrai PRINTF : |%03.4llx|\n", (unsigned long long)10);
	ft_printf("16) Mon PRINTF  : |%03.4llx|\n", (unsigned long long)10);
	printf("17) Vrai PRINTF : |%#llx|\n", (unsigned long long)34);
	ft_printf("17) Mon PRINTF  : |%#llx|\n", (unsigned long long)34);
	printf("18) Vrai PRINTF : |%#.5llx|\n", (unsigned long long)34);
	ft_printf("18) Mon PRINTF  : |%#.5llx|\n", (unsigned long long)34);
	printf("19) Vrai PRINTF : |%#5llx|\n", (unsigned long long)86);
	ft_printf("19) Mon PRINTF  : |%#5llx|\n", (unsigned long long)86);
	printf("20) Vrai PRINTF : |%#10.5llx|\n", (unsigned long long)70);
	ft_printf("20) Mon PRINTF  : |%#10.5llx|\n", (unsigned long long)70);
	printf("21) Vrai PRINTF : |%#llx|\n", (unsigned long long)0);
	ft_printf("21) Mon PRINTF  : |%#llx|\n", (unsigned long long)0);
	printf("22) Vrai PRINTF : |%#.llx|\n", (unsigned long long)0);
	ft_printf("22) Mon PRINTF  : |%#.llx|\n", (unsigned long long)0);
	printf("23) Vrai PRINTF : |%.llx|\n", (unsigned long long)0);
	ft_printf("23) Mon PRINTF  : |%.llx|\n", (unsigned long long)0);
	printf("24) Vrai PRINTF : |%.llx|\n", (unsigned long long)88);
	ft_printf("24) Mon PRINTF  : |%.llx|\n", (unsigned long long)88);
	printf("25) Vrai PRINTF : |%#.llx|\n", (unsigned long long)88);
	ft_printf("25) Mon PRINTF  : |%#.llx|\n", (unsigned long long)88);
	printf("26) Vrai PRINTF : |%llx|\n", (unsigned long long)UINT_MAX);
	ft_printf("26) Mon PRINTF  : |%llx|\n", (unsigned long long)UINT_MAX);
	printf("27) Vrai PRINTF : |%#llx|\n", (unsigned long long)-1, ULLONG_MAX);
	ft_printf("27) Mon PRINTF  : |%#llx|\n", (unsigned long long)-1, ULLONG_MAX);
	printf("28) Vrai PRINTF : |%#llx| |%#llx|\n", (unsigned long long)-1, ULLONG_MAX + 1);
	ft_printf("28) Mon PRINTF  : |%#llx| |%#llx|\n", (unsigned long long)-1, ULLONG_MAX + 1);
	ft_printf("--------------------%%X--------------------\n");
	printf("01) Vrai PRINTF : |%X|\n", 34);
	ft_printf("01) Mon PRINTF  : |%X|\n", 34);
	printf("02) Vrai PRINTF : |%X|\n", -34);
	ft_printf("02) Mon PRINTF  : |%X|\n", -34);
	printf("03) Vrai PRINTF : |%-X|\n", 50);
	ft_printf("03) Mon PRINTF  : |%-X|\n", 50);
	printf("04) Vrai PRINTF : |%10X|\n", 90);
	ft_printf("04) Mon PRINTF  : |%10X|\n", 90);
	printf("05) Vrai PRINTF : |%.10X|\n", 90);
	ft_printf("05) Mon PRINTF  : |%.10X|\n", 90);
	printf("06) Vrai PRINTF : |%15X|\n", -100);
	ft_printf("06) Mon PRINTF  : |%15X|\n", -100);
	printf("07) Vrai PRINTF : |%.15X|\n", -100);
	ft_printf("07) Mon PRINTF  : |%.15X|\n", -100);
	printf("08) Vrai PRINTF : |%10.5X|\n", 52);
	ft_printf("08) Mon PRINTF  : |%10.5X|\n", 52);
	printf("09) Vrai PRINTF : |%5.10X|\n", 52);
	ft_printf("09) Mon PRINTF  : |%5.10X|\n", 52);
	printf("10) Vrai PRINTF : |%20.15X|\n", -100000);
	ft_printf("10) Mon PRINTF  : |%20.15X|\n", -100000);
	printf("11) Vrai PRINTF : |%15.20X|\n", -100000);
	ft_printf("11) Mon PRINTF  : |%15.20X|\n", -100000);
	printf("12) Vrai PRINTF : |%-10X|\n", 144);
	ft_printf("12) Mon PRINTF  : |%-10X|\n", 144);
	printf("13) Vrai PRINTF : |%-.10X|\n", 144);
	ft_printf("13) Mon PRINTF  : |%-.10X|\n", 144);
	printf("14) Vrai PRINTF : |%-20X|\n", -20000000);
	ft_printf("14) Mon PRINTF  : |%-20X|\n", -20000000);
	printf("15) Vrai PRINTF : |%08X|\n", 64);
	ft_printf("15) Mon PRINTF  : |%08X|\n", 64);
	printf("16) Vrai PRINTF : |%03.4X|\n", 10);
	ft_printf("16) Mon PRINTF  : |%03.4X|\n", 10);
	printf("17) Vrai PRINTF : |%#X|\n", 34);
	ft_printf("17) Mon PRINTF  : |%#X|\n", 34);
	printf("18) Vrai PRINTF : |%#.5X|\n", 34);
	ft_printf("18) Mon PRINTF  : |%#.5X|\n", 34);
	printf("19) Vrai PRINTF : |%#5X|\n", 86);
	ft_printf("19) Mon PRINTF  : |%#5X|\n", 86);
	printf("20) Vrai PRINTF : |%#10.5X|\n", 70);
	ft_printf("20) Mon PRINTF  : |%#10.5X|\n", 70);
	printf("21) Vrai PRINTF : |%#X|\n", 0);
	ft_printf("21) Mon PRINTF  : |%#X|\n", 0);
	printf("22) Vrai PRINTF : |%#.X|\n", 0);
	ft_printf("22) Mon PRINTF  : |%#.X|\n", 0);
	printf("23) Vrai PRINTF : |%.X|\n", 0);
	ft_printf("23) Mon PRINTF  : |%.X|\n", 0);
	printf("24) Vrai PRINTF : |%.X|\n", 88);
	ft_printf("24) Mon PRINTF  : |%.X|\n", 88);
	printf("25) Vrai PRINTF : |%#.X|\n", 88);
	ft_printf("25) Mon PRINTF  : |%#.X|\n", 88);
	printf("26) Vrai PRINTF : |%X|\n", UINT_MAX);
	ft_printf("26) Mon PRINT   : |%X|\n", UINT_MAX);
	printf("27) Vrai PRINTF : |%#X|\n", UINT_MAX);
	ft_printf("27) Mon PRINTF  : |%#X|\n", UINT_MAX);
	printf("28) Vrai PRINTF : |%#X| |%#X|\n", (unsigned int)-1, UINT_MAX + 1);
	ft_printf("28) Mon PRINTF  : |%#X| |%#X|\n", (unsigned int)-1, UINT_MAX + 1);
	ft_printf("--------------------%%hX--------------------\n");
	printf("01) Vrai PRINTF : |%hX|\n", (unsigned short)34);
	ft_printf("01) Mon PRINTF  : |%hX|\n", (unsigned short)34);
	printf("02) Vrai PRINTF : |%hX|\n", (unsigned short)-34);
	ft_printf("02) Mon PRINTF  : |%hX|\n", (unsigned short)-34);
	printf("03) Vrai PRINTF : |%-hX|\n", (unsigned short)50);
	ft_printf("03) Mon PRINTF  : |%-hX|\n", (unsigned short)50);
	printf("04) Vrai PRINTF : |%10hX|\n", (unsigned short)90);
	ft_printf("04) Mon PRINTF  : |%10hX|\n", (unsigned short)90);
	printf("05) Vrai PRINTF : |%.10hX|\n", (unsigned short)90);
	ft_printf("05) Mon PRINTF  : |%.10hX|\n", (unsigned short)90);
	printf("06) Vrai PRINTF : |%15hX|\n", (unsigned short)-100);
	ft_printf("06) Mon PRINTF  : |%15hX|\n", (unsigned short)-100);
	printf("07) Vrai PRINTF : |%.15hX|\n", (unsigned short)-100);
	ft_printf("07) Mon PRINTF  : |%.15hX|\n", (unsigned short)-100);
	printf("08) Vrai PRINTF : |%10.5hX|\n", (unsigned short)52);
	ft_printf("08) Mon PRINTF  : |%10.5hX|\n", (unsigned short)52);
	printf("09) Vrai PRINTF : |%5.10hX|\n", (unsigned short)52);
	ft_printf("09) Mon PRINTF  : |%5.10hX|\n", (unsigned short)52);
	printf("10) Vrai PRINTF : |%20.15hX|\n", (unsigned short)-10000);
	ft_printf("10) Mon PRINTF  : |%20.15hX|\n", (unsigned short)-10000);
	printf("11) Vrai PRINTF : |%15.20hX|\n", (unsigned short)-10000);
	ft_printf("11) Mon PRINTF  : |%15.20hX|\n", (unsigned short)-10000);
	printf("12) Vrai PRINTF : |%-10hX|\n", (unsigned short)144);
	ft_printf("12) Mon PRINTF  : |%-10hX|\n", (unsigned short)144);
	printf("13) Vrai PRINTF : |%-.10hX|\n", (unsigned short)144);
	ft_printf("13) Mon PRINTF  : |%-.10hX|\n", (unsigned short)144);
	printf("14) Vrai PRINTF : |%-20hX|\n", (unsigned short)-20000);
	ft_printf("14) Mon PRINTF  : |%-20hX|\n", (unsigned short)-20000);
	printf("15) Vrai PRINTF : |%08hX|\n", (unsigned short)64);
	ft_printf("15) Mon PRINTF  : |%08hX|\n", (unsigned short)64);
	printf("16) Vrai PRINTF : |%03.4hX|\n", (unsigned short)10);
	ft_printf("16) Mon PRINTF  : |%03.4hX|\n", (unsigned short)10);
	printf("17) Vrai PRINTF : |%#hX|\n", (unsigned short)34);
	ft_printf("17) Mon PRINTF  : |%#hX|\n", (unsigned short)34);
	printf("18) Vrai PRINTF : |%#.5hX|\n", (unsigned short)34);
	ft_printf("18) Mon PRINTF  : |%#.5hX|\n", (unsigned short)34);
	printf("19) Vrai PRINTF : |%#5hX|\n", (unsigned short)86);
	ft_printf("19) Mon PRINTF  : |%#5hX|\n", (unsigned short)86);
	printf("20) Vrai PRINTF : |%#10.5hX|\n", (unsigned short)70);
	ft_printf("20) Mon PRINTF  : |%#10.5hX|\n", (unsigned short)70);
	printf("21) Vrai PRINTF : |%#hX|\n", (unsigned short)0);
	ft_printf("21) Mon PRINTF  : |%#hX|\n", (unsigned short)0);
	printf("22) Vrai PRINTF : |%#.hX|\n", (unsigned short)0);
	ft_printf("22) Mon PRINTF  : |%#.hX|\n", (unsigned short)0);
	printf("23) Vrai PRINTF : |%.hX|\n", (unsigned short)0);
	ft_printf("23) Mon PRINTF  : |%.hX|\n", (unsigned short)0);
	printf("24) Vrai PRINTF : |%.hX|\n", (unsigned short)88);
	ft_printf("24) Mon PRINTF  : |%.hX|\n", (unsigned short)88);
	printf("25) Vrai PRINTF : |%#.hX|\n", (unsigned short)88);
	ft_printf("25) Mon PRINTF  : |%#.hX|\n", (unsigned short)88);
	printf("26) Vrai PRINTF : |%hX|\n", (unsigned short)USHRT_MAX);
	ft_printf("26) Mon PRINTF  : |%hX|\n", (unsigned short)USHRT_MAX);
	printf("27) Vrai PRINTF : |%#hX|\n", (unsigned short)USHRT_MAX);
	ft_printf("27) Mon PRINTF  : |%#hX|\n", (unsigned short)USHRT_MAX);
	printf("28) Vrai PRINTF : |%#hX| |%#hX|\n", (unsigned short)-1, (unsigned short)65536);
	ft_printf("28) Mon PRINTF  : |%#hX| |%#hX|\n", (unsigned short)-1, (unsigned short)65536);
	ft_printf("--------------------%%hhX--------------------\n");
	printf("01) Vrai PRINTF : |%hhX|\n", (unsigned char)34);
	ft_printf("01) Mon PRINTF  : |%hhX|\n", (unsigned char)34);
	printf("02) Vrai PRINTF : |%hhX|\n", (unsigned char)-34);
	ft_printf("02) Mon PRINTF  : |%hhX|\n", (unsigned char)-34);
	printf("03) Vrai PRINTF : |%-hhX|\n", (unsigned char)50);
	ft_printf("03) Mon PRINTF  : |%-hhX|\n", (unsigned char)50);
	printf("04) Vrai PRINTF : |%10hhX|\n", (unsigned char)90);
	ft_printf("04) Mon PRINTF  : |%10hhX|\n", (unsigned char)90);
	printf("05) Vrai PRINTF : |%.10hhX|\n", (unsigned char)90);
	ft_printf("05) Mon PRINTF  : |%.10hhX|\n", (unsigned char)90);
	printf("06) Vrai PRINTF : |%15hhX|\n", (unsigned char)-100);
	ft_printf("06) Mon PRINTF  : |%15hhX|\n", (unsigned char)-100);
	printf("07) Vrai PRINTF : |%.15hhX|\n", (unsigned char)-100);
	ft_printf("07) Mon PRINTF  : |%.15hhX|\n", (unsigned char)-100);
	printf("08) Vrai PRINTF : |%10.5hhX|\n", (unsigned char)52);
	ft_printf("08) Mon PRINTF  : |%10.5hhX|\n", (unsigned char)52);
	printf("09) Vrai PRINTF : |%5.10hhX|\n", (unsigned char)52);
	ft_printf("09) Mon PRINTF  : |%5.10hhX|\n", (unsigned char)52);
	printf("10) Vrai PRINTF : |%20.15hhX|\n", (unsigned char)-10000);
	ft_printf("10) Mon PRINTF  : |%20.15hhX|\n", (unsigned char)-10000);
	printf("11) Vrai PRINTF : |%15.20hhX|\n", (unsigned char)-10000);
	ft_printf("11) Mon PRINTF  : |%15.20hhX|\n", (unsigned char)-10000);
	printf("12) Vrai PRINTF : |%-10hhX|\n", (unsigned char)144);
	ft_printf("12) Mon PRINTF  : |%-10hhX|\n", (unsigned char)144);
	printf("13) Vrai PRINTF : |%-.10hhX|\n", (unsigned char)144);
	ft_printf("13) Mon PRINTF  : |%-.10hhX|\n", (unsigned char)144);
	printf("14) Vrai PRINTF : |%-20hhX|\n", (unsigned char)-20000);
	ft_printf("14) Mon PRINTF  : |%-20hhX|\n", (unsigned char)-20000);
	printf("15) Vrai PRINTF : |%08hhX|\n", (unsigned char)64);
	ft_printf("15) Mon PRINTF  : |%08hhX|\n", (unsigned char)64);
	printf("16) Vrai PRINTF : |%03.4hhX|\n", (unsigned char)10);
	ft_printf("16) Mon PRINTF  : |%03.4hhX|\n", (unsigned char)10);
	printf("17) Vrai PRINTF : |%#hhX|\n", (unsigned char)34);
	ft_printf("17) Mon PRINTF  : |%#hhX|\n", (unsigned char)34);
	printf("18) Vrai PRINTF : |%#.5hhX|\n", (unsigned char)34);
	ft_printf("18) Mon PRINTF  : |%#.5hhX|\n", (unsigned char)34);
	printf("19) Vrai PRINTF : |%#5hhX|\n", (unsigned char)86);
	ft_printf("19) Mon PRINTF  : |%#5hhX|\n", (unsigned char)86);
	printf("20) Vrai PRINTF : |%#10.5hhX|\n", (unsigned char)70);
	ft_printf("20) Mon PRINTF  : |%#10.5hhX|\n", (unsigned char)70);
	printf("21) Vrai PRINTF : |%#hhX|\n", (unsigned char)0);
	ft_printf("21) Mon PRINTF  : |%#hhX|\n", (unsigned char)0);
	printf("22) Vrai PRINTF : |%#.hhX|\n", (unsigned char)0);
	ft_printf("22) Mon PRINTF  : |%#.hhX|\n", (unsigned char)0);
	printf("23) Vrai PRINTF : |%.hhX|\n", (unsigned char)0);
	ft_printf("23) Mon PRINTF  : |%.hhX|\n", (unsigned char)0);
	printf("24) Vrai PRINTF : |%.hhX|\n", (unsigned char)88);
	ft_printf("24) Mon PRINTF  : |%.hhX|\n", (unsigned char)88);
	printf("25) Vrai PRINTF : |%#.hhX|\n", (unsigned char)88);
	ft_printf("25) Mon PRINTF  : |%#.hhX|\n", (unsigned char)88);
	printf("26) Vrai PRINTF : |%hhX|\n", (unsigned char)255);
	ft_printf("26) Mon PRINTF  : |%hhX|\n", (unsigned char)255);
	printf("27) Vrai PRINTF : |%#hhX|\n", (unsigned char)255);
	ft_printf("27) Mon PRINTF  : |%#hhX|\n", (unsigned char)255);
	printf("28) Vrai PRINTF : |%#hhX| |%#hhX|\n", (unsigned char)-1, (unsigned char)256);
	ft_printf("28) Mon PRINTF  : |%#hhX| |%#hhX|\n", (unsigned char)-1, (unsigned char) 256);
	ft_printf("--------------------%%lX--------------------\n");
	printf("01) Vrai PRINTF : |%lX|\n",(unsigned long)34);
	ft_printf("01) Mon PRINTF  : |%lX|\n", (unsigned long)34);
	printf("02) Vrai PRINTF : |%lX|\n", (unsigned long)-34);
	ft_printf("02) Mon PRINTF  : |%lX|\n", (unsigned long)-34);
	printf("03) Vrai PRINTF : |%-lX|\n", (unsigned long)50);
	ft_printf("03) Mon PRINTF  : |%-lX|\n", (unsigned long)50);
	printf("04) Vrai PRINTF : |%10lX|\n", (unsigned long)90);
	ft_printf("04) Mon PRINTF  : |%10lX|\n", (unsigned long)90);
	printf("05) Vrai PRINTF : |%.10lX|\n", (unsigned long)90);
	ft_printf("05) Mon PRINTF  : |%.10lX|\n", (unsigned long)90);
	printf("06) Vrai PRINTF : |%15lX|\n", (unsigned long)-100);
	ft_printf("06) Mon PRINTF  : |%15lX|\n", (unsigned long)-100);
	printf("07) Vrai PRINTF : |%.15lX|\n", (unsigned long)-100);
	ft_printf("07) Mon PRINTF  : |%.15lX|\n", (unsigned long)-100);
	printf("08) Vrai PRINTF : |%10.5lX|\n", (unsigned long)52);
	ft_printf("08) Mon PRINTF  : |%10.5lX|\n", (unsigned long)52);
	printf("09) Vrai PRINTF : |%5.10lX|\n", (unsigned long)52);
	ft_printf("09) Mon PRINTF  : |%5.10lX|\n", (unsigned long)52);
	printf("10) Vrai PRINTF : |%20.15lX|\n", (unsigned long)-100000);
	ft_printf("10) Mon PRINTF  : |%20.15lX|\n", (unsigned long)-100000);
	printf("11) Vrai PRINTF : |%15.20lX|\n", (unsigned long)-100000);
	ft_printf("11) Mon PRINTF  : |%15.20lX|\n", (unsigned long)-100000);
	printf("12) Vrai PRINTF : |%-10lX|\n", (unsigned long)144);
	ft_printf("12) Mon PRINTF  : |%-10lX|\n", (unsigned long)144);
	printf("13) Vrai PRINTF : |%-.10lX|\n", (unsigned long)144);
	ft_printf("13) Mon PRINTF  : |%-.10lX|\n", (unsigned long)144);
	printf("14) Vrai PRINTF : |%-20lX|\n", (unsigned long)-20000000);
	ft_printf("14) Mon PRINTF  : |%-20lX|\n", (unsigned long)-20000000);
	printf("15) Vrai PRINTF : |%08lX|\n", (unsigned long)64);
	ft_printf("15) Mon PRINTF  : |%08lX|\n", (unsigned long)64);
	printf("16) Vrai PRINTF : |%03.4lX|\n", (unsigned long)10);
	ft_printf("16) Mon PRINTF  : |%03.4lX|\n", (unsigned long)10);
	printf("17) Vrai PRINTF : |%#lX|\n", (unsigned long)34);
	ft_printf("17) Mon PRINTF  : |%#lX|\n", (unsigned long)34);
	printf("18) Vrai PRINTF : |%#.5lX|\n", (unsigned long)34);
	ft_printf("18) Mon PRINTF  : |%#.5lX|\n", (unsigned long)34);
	printf("19) Vrai PRINTF : |%#5lX|\n", (unsigned long)86);
	ft_printf("19) Mon PRINTF  : |%#5lX|\n", (unsigned long)86);
	printf("20) Vrai PRINTF : |%#10.5lX|\n", (unsigned long)70);
	ft_printf("20) Mon PRINTF  : |%#10.5lX|\n", (unsigned long)70);
	printf("21) Vrai PRINTF : |%#lX|\n", (unsigned long)0);
	ft_printf("21) Mon PRINTF  : |%#lX|\n", (unsigned long)0);
	printf("22) Vrai PRINTF : |%#.lX|\n", (unsigned long)0);
	ft_printf("22) Mon PRINTF  : |%#.lX|\n", (unsigned long)0);
	printf("23) Vrai PRINTF : |%.lX|\n", (unsigned long)0);
	ft_printf("23) Mon PRINTF  : |%.lX|\n", (unsigned long)0);
	printf("24) Vrai PRINTF : |%.lX|\n", (unsigned long)88);
	ft_printf("24) Mon PRINTF  : |%.lX|\n", (unsigned long)88);
	printf("25) Vrai PRINTF : |%#.lX|\n", (unsigned long)88);
	ft_printf("25) Mon PRINTF  : |%#.lX|\n", (unsigned long)88);
	printf("26) Vrai PRINTF : |%lX|\n", (unsigned long)UINT_MAX);
	ft_printf("26) Mon PRINTF  : |%lX|\n", (unsigned long)UINT_MAX);
	printf("27) Vrai PRINTF : |%#lX|\n", (unsigned long)-1, ULONG_MAX);
	ft_printf("27) Mon PRINTF  : |%#lX|\n", (unsigned long)-1, ULONG_MAX);
	printf("28) Vrai PRINTF : |%#lX| |%#lX|\n", (unsigned long)-1, ULONG_MAX + 1);
	ft_printf("28) Mon PRINTF  : |%#lX| |%#lX|\n", (unsigned long)-1, ULONG_MAX + 1);
	ft_printf("--------------------%%llX--------------------\n");
	printf("01) Vrai PRINTF : |%llX|\n",(unsigned long long)34);
	ft_printf("01) Mon PRINTF  : |%llX|\n", (unsigned long long)34);
	printf("02) Vrai PRINTF : |%llX|\n", (unsigned long long)-34);
	ft_printf("02) Mon PRINTF  : |%llX|\n", (unsigned long long)-34);
	printf("03) Vrai PRINTF : |%-llX|\n", (unsigned long long)50);
	ft_printf("03) Mon PRINTF  : |%-llX|\n", (unsigned long long)50);
	printf("04) Vrai PRINTF : |%10llX|\n", (unsigned long long)90);
	ft_printf("04) Mon PRINTF  : |%10llX|\n", (unsigned long long)90);
	printf("05) Vrai PRINTF : |%.10llX|\n", (unsigned long long)90);
	ft_printf("05) Mon PRINTF  : |%.10llX|\n", (unsigned long long)90);
	printf("06) Vrai PRINTF : |%15llX|\n", (unsigned long long)-100);
	ft_printf("06) Mon PRINTF  : |%15llX|\n", (unsigned long long)-100);
	printf("07) Vrai PRINTF : |%.15llX|\n", (unsigned long long)-100);
	ft_printf("07) Mon PRINTF  : |%.15llX|\n", (unsigned long long)-100);
	printf("08) Vrai PRINTF : |%10.5llX|\n", (unsigned long long)52);
	ft_printf("08) Mon PRINTF  : |%10.5llX|\n", (unsigned long long)52);
	printf("09) Vrai PRINTF : |%5.10llX|\n", (unsigned long long)52);
	ft_printf("09) Mon PRINTF  : |%5.10llX|\n", (unsigned long long)52);
	printf("10) Vrai PRINTF : |%20.15llX|\n", (unsigned long long)-100000);
	ft_printf("10) Mon PRINTF  : |%20.15llX|\n", (unsigned long long)-100000);
	printf("11) Vrai PRINTF : |%15.20llX|\n", (unsigned long long)-100000);
	ft_printf("11) Mon PRINTF  : |%15.20llX|\n", (unsigned long long)-100000);
	printf("12) Vrai PRINTF : |%-10llX|\n", (unsigned long long)144);
	ft_printf("12) Mon PRINTF  : |%-10llX|\n", (unsigned long long)144);
	printf("13) Vrai PRINTF : |%-.10llX|\n", (unsigned long long)144);
	ft_printf("13) Mon PRINTF  : |%-.10llX|\n", (unsigned long long)144);
	printf("14) Vrai PRINTF : |%-20llX|\n", (unsigned long long)-20000000);
	ft_printf("14) Mon PRINTF  : |%-20llX|\n", (unsigned long long)-20000000);
	printf("15) Vrai PRINTF : |%08llX|\n", (unsigned long long)64);
	ft_printf("15) Mon PRINTF  : |%08llX|\n", (unsigned long long)64);
	printf("16) Vrai PRINTF : |%03.4llX|\n", (unsigned long long)10);
	ft_printf("16) Mon PRINTF  : |%03.4llX|\n", (unsigned long long)10);
	printf("17) Vrai PRINTF : |%#llX|\n", (unsigned long long)34);
	ft_printf("17) Mon PRINTF  : |%#llX|\n", (unsigned long long)34);
	printf("18) Vrai PRINTF : |%#.5llX|\n", (unsigned long long)34);
	ft_printf("18) Mon PRINTF  : |%#.5llX|\n", (unsigned long long)34);
	printf("19) Vrai PRINTF : |%#5llX|\n", (unsigned long long)86);
	ft_printf("19) Mon PRINTF  : |%#5llX|\n", (unsigned long long)86);
	printf("20) Vrai PRINTF : |%#10.5llX|\n", (unsigned long long)70);
	ft_printf("20) Mon PRINTF  : |%#10.5llX|\n", (unsigned long long)70);
	printf("21) Vrai PRINTF : |%#llX|\n", (unsigned long long)0);
	ft_printf("21) Mon PRINTF  : |%#llX|\n", (unsigned long long)0);
	printf("22) Vrai PRINTF : |%#.llX|\n", (unsigned long long)0);
	ft_printf("22) Mon PRINTF  : |%#.llX|\n", (unsigned long long)0);
	printf("23) Vrai PRINTF : |%.llX|\n", (unsigned long long)0);
	ft_printf("23) Mon PRINTF  : |%.llX|\n", (unsigned long long)0);
	printf("24) Vrai PRINTF : |%.llX|\n", (unsigned long long)88);
	ft_printf("24) Mon PRINTF  : |%.llX|\n", (unsigned long long)88);
	printf("25) Vrai PRINTF : |%#.llX|\n", (unsigned long long)88);
	ft_printf("25) Mon PRINTF  : |%#.llX|\n", (unsigned long long)88);
	printf("26) Vrai PRINTF : |%llX|\n", (unsigned long long)UINT_MAX);
	ft_printf("26) Mon PRINTF  : |%llX|\n", (unsigned long long)UINT_MAX);
	printf("27) Vrai PRINTF : |%#llX|\n", (unsigned long long)-1, ULLONG_MAX);
	ft_printf("27) Mon PRINTF  : |%#llX|\n", (unsigned long long)-1, ULLONG_MAX);
	printf("28) Vrai PRINTF : |%#llX| |%#llX|\n", (unsigned long long)-1, ULLONG_MAX + 1);
	ft_printf("28) Mon PRINTF  : |%#llX| |%#llX|\n", (unsigned long long)-1, ULLONG_MAX + 1);
}
