#include <stdio.h>
#include "srcs/ft_printf.h"

int		main(void)
{
		ft_printf("--------------------%%u--------------------\n");
	printf("01) Vrai PRINTF : |%u|\n", 34);
	ft_printf("01) Mon PRINTF  : |%u|\n", 34);
	printf("02) Vrai PRINTF : |%u|\n", -34);
	ft_printf("02) Mon PRINTF  : |%u|\n", -34);
	printf("03) Vrai PRINTF : |%-u|\n", 50);
	ft_printf("03) Mon PRINTF  : |%-u|\n", 50);
	printf("04) Vrai PRINTF : |%10u|\n", 90);
	ft_printf("04) Mon PRINTF  : |%10u|\n", 90);
	printf("05) Vrai PRINTF : |%.10u|\n", 90);
	ft_printf("05) Mon PRINTF  : |%.10u|\n", 90);
	printf("06) Vrai PRINTF : |%15u|\n", -100);
	ft_printf("06) Mon PRINTF  : |%15u|\n", -100);
	printf("07) Vrai PRINTF : |%.15u|\n", -100);
	ft_printf("07) Mon PRINTF  : |%.15u|\n", -100);
	printf("08) Vrai PRINTF : |%10.5u|\n", 52);
	ft_printf("08) Mon PRINTF  : |%10.5u|\n", 52);
	printf("09) Vrai PRINTF : |%5.10u|\n", 52);
	ft_printf("09) Mon PRINTF  : |%5.10u|\n", 52);
	printf("10) Vrai PRINTF : |%20.15u|\n", -100000);
	ft_printf("10) Mon PRINTF  : |%20.15u|\n", -100000);
	printf("11) Vrai PRINTF : |%15.20u|\n", -100000);
	ft_printf("11) Mon PRINTF  : |%15.20u|\n", -100000);
	printf("12) Vrai PRINTF : |%-10u|\n", 144);
	ft_printf("12) Mon PRINTF  : |%-10u|\n", 144);
	printf("13) Vrai PRINTF : |%-.10u|\n", 144);
	ft_printf("13) Mon PRINTF  : |%-.10u|\n", 144);
	printf("14) Vrai PRINTF : |%-20u|\n", -20000000);
	ft_printf("14) Mon PRINTF  : |%-20u|\n", -20000000);
	printf("15) Vrai PRINTF : |%08u|\n", 64);
	ft_printf("15) Mon PRINTF  : |%08u|\n", 64);
	printf("16) Vrai PRINTF : |%03.4u|\n", 10);
	ft_printf("16) Mon PRINTF  : |%03.4u|\n", 10);
	printf("17) Vrai PRINTF : |%.u|\n", 0);
	ft_printf("17) Mon PRINTF  : |%.u|\n", 0);
	printf("18) Vrai PRINTF : |%.u|\n", 88);
	ft_printf("18) Mon PRINTF  : |%.u|\n", 88);
	printf("19) Vrai PRINTF : |%u|\n", UINT_MAX);
	ft_printf("19) Mon PRINTF  : |%u|\n", UINT_MAX);
	printf("20) Vrai PRINTF : |%u| |%u|\n", (unsigned int)-1, UINT_MAX + 1);
	ft_printf("20) Mon PRINTF  : |%u| |%u|\n", (unsigned int)-1, UINT_MAX + 1);
	printf("21) Vrai PRINTF : |%u| |%u| |%u| |%u| |%u| |%u|\n", 42, 100, 25, 16, 30, 69);
	ft_printf("21) Mon PRINTF  : |%u| |%u| |%u| |%u| |%u| |%u|\n", 42, 100, 25, 16, 30, 69);
	printf("22) Vrai PRINTF : |%10u| |%-10u| |%.5u| |%-.5u| |%-u|\n", 42, 100, 25, 16, 30);
	ft_printf("22) Mon PRINTF  : |%10u| |%-10u| |%.5u| |%-.5u| |%-u|\n", 42, 100, 25, 16, 30);
	printf("23) Vrai PRINTF : |%u| |%u| |%u| |%u| |%u| |%u|\n", -42, -100, -25, -16, -30, -69);
	ft_printf("23) Mon PRINTF  : |%u| |%u| |%u| |%u| |%u| |%u|\n", -42, -100, -25, -16, -30, -69);
	printf("24) Vrai PRINTF : |%10u| |%-10u| |%.5u| |%-.5u| |%-u|\n", -42, -100, -25, -16, -30);
	ft_printf("24) Mon PRINTF  : |%10u| |%-10u| |%.5u| |%-.5u| |%-u|\n", -42, -100, -25, -16, -30);
	ft_printf("--------------------%%hu--------------------\n");
	printf("01) Vrai PRINTF : |%hu|\n", (unsigned short)34);
	ft_printf("01) Mon PRINTF  : |%hu|\n", (unsigned short)34);
	printf("02) Vrai PRINTF : |%hu|\n", (unsigned short)-34);
	ft_printf("02) Mon PRINTF  : |%hu|\n", (unsigned short)-34);
	printf("03) Vrai PRINTF : |%-hu|\n", (unsigned short)50);
	ft_printf("03) Mon PRINTF  : |%-hu|\n", (unsigned short)50);
	printf("04) Vrai PRINTF : |%10hu|\n", (unsigned short)90);
	ft_printf("04) Mon PRINTF  : |%10hu|\n", (unsigned short)90);
	printf("05) Vrai PRINTF : |%.10hu|\n", (unsigned short)90);
	ft_printf("05) Mon PRINTF  : |%.10hu|\n", (unsigned short)90);
	printf("06) Vrai PRINTF : |%15hu|\n", (unsigned short)-100);
	ft_printf("06) Mon PRINTF  : |%15hu|\n", (unsigned short)-100);
	printf("07) Vrai PRINTF : |%.15hu|\n", (unsigned short)-100);
	ft_printf("07) Mon PRINTF  : |%.15hu|\n", (unsigned short)-100);
	printf("08) Vrai PRINTF : |%10.5hu|\n", (unsigned short)52);
	ft_printf("08) Mon PRINTF  : |%10.5hu|\n", (unsigned short)52);
	printf("09) Vrai PRINTF : |%5.10hu|\n", (unsigned short)52);
	ft_printf("09) Mon PRINTF  : |%5.10hu|\n", (unsigned short)52);
	printf("10) Vrai PRINTF : |%20.15hu|\n", (unsigned short)-10000);
	ft_printf("10) Mon PRINTF  : |%20.15hu|\n", (unsigned short)-10000);
	printf("11) Vrai PRINTF : |%15.20hu|\n", (unsigned short)-10000);
	ft_printf("11) Mon PRINTF  : |%15.20hu|\n", (unsigned short)-10000);
	printf("12) Vrai PRINTF : |%-10hu|\n", (unsigned short)144);
	ft_printf("12) Mon PRINTF  : |%-10hu|\n", (unsigned short)144);
	printf("13) Vrai PRINTF : |%-.10hu|\n", (unsigned short)144);
	ft_printf("13) Mon PRINTF  : |%-.10hu|\n", (unsigned short)144);
	printf("14) Vrai PRINTF : |%-20hu|\n", (unsigned short)-20000);
	ft_printf("14) Mon PRINTF  : |%-20hu|\n", (unsigned short)-20000);
	printf("15) Vrai PRINTF : |%08hu|\n", (unsigned short)64);
	ft_printf("15) Mon PRINTF  : |%08hu|\n", (unsigned short)64);
	printf("16) Vrai PRINTF : |%03.4hu|\n", (unsigned short)10);
	ft_printf("16) Mon PRINTF  : |%03.4hu|\n", (unsigned short)10);                                                          
	printf("17) Vrai PRINTF : |%.hu|\n", (unsigned short)0);
	ft_printf("17) Mon PRINTF  : |%.hu|\n", (unsigned short)0);
	printf("18) Vrai PRINTF : |%.hu|\n", (unsigned short)88);
	ft_printf("18) Mon PRINTF  : |%.hu|\n", (unsigned short)88);
	printf("19) Vrai PRINTF : |%hu|\n", (unsigned short)USHRT_MAX);
	ft_printf("19) Mon PRINTF  : |%hu|\n", (unsigned short)USHRT_MAX);
	printf("20) Vrai PRINTF : |%hu| |%hu|\n", (unsigned short)-1, (unsigned short)65536);
	ft_printf("20) Mon PRINTF  : |%hu| |%hu|\n", (unsigned short)-1, (unsigned short)65536);
	printf("21) Vrai PRINTF : |%hu| |%hu| |%hu| |%hu| |%hu| |%hu|\n", (unsigned short)42, (unsigned short)100, (unsigned short)25, (unsigned short)16, (unsigned short)30, (unsigned short)69);
	ft_printf("21) Mon PRINTF  : |%hu| |%hu| |%hu| |%hu| |%hu| |%hu|\n", (unsigned short)42, (unsigned short)100, (unsigned short)25, (unsigned short)16, (unsigned short)30, (unsigned short)69);
	printf("22) Vrai PRINTF : |%10hu| |%-10hu| |%.5hu| |%-.5hu| |%-hu|\n", (unsigned short)42, (unsigned short)100, (unsigned short)25, (unsigned short)16, (unsigned short)30);
	ft_printf("22) Mon PRINTF  : |%10hu| |%-10hu| |%.5hu| |%-.5hu| |%-hu|\n", (unsigned short)42, (unsigned short)100, (unsigned short)25, (unsigned short)16, (unsigned short)30);
	printf("23) Vrai PRINTF : |%hu| |%hu| |%hu| |%hu| |%hu| |%hu|\n", (unsigned short)-42, (unsigned short)-100, (unsigned short)-25, (unsigned short)-16, (unsigned short)-30, (unsigned short)-69);
	ft_printf("23) Mon PRINTF  : |%hu| |%hu| |%hu| |%hu| |%hu| |%hu|\n", (unsigned short)-42, (unsigned short)-100, (unsigned short)-25, (unsigned short)-16, (unsigned short)-30, (unsigned short)-69);
	printf("24) Vrai PRINTF : |%10hu| |%-10hu| |%.5hu| |%-.5hu| |%-hu|\n", (unsigned short)-42, (unsigned short)-100, (unsigned short)-25, (unsigned short)-16, (unsigned short)-30);
	ft_printf("24) Mon PRINTF  : |%10hu| |%-10hu| |%.5hu| |%-.5hu| |%-hu|\n", (unsigned short)-42, (unsigned short)-100, (unsigned short)-25, (unsigned short)-16, (unsigned short)-30);
	ft_printf("--------------------%%hhu--------------------\n");
	printf("01) Vrai PRINTF : |%hhu|\n", (unsigned char)34);
	ft_printf("01) Mon PRINTF  : |%hhu|\n", (unsigned char)34);
	printf("02) Vrai PRINTF : |%hhu|\n", (unsigned char)-34);
	ft_printf("02) Mon PRINTF  : |%hhu|\n", (unsigned char)-34);
	printf("03) Vrai PRINTF : |%-hhu|\n", (unsigned char)50);
	ft_printf("03) Mon PRINTF  : |%-hhu|\n", (unsigned char)50);
	printf("04) Vrai PRINTF : |%10hhu|\n", (unsigned char)90);
	ft_printf("04) Mon PRINTF  : |%10hhu|\n", (unsigned char)90);
	printf("05) Vrai PRINTF : |%.10hhu|\n", (unsigned char)90);
	ft_printf("05) Mon PRINTF  : |%.10hhu|\n", (unsigned char)90);
	printf("06) Vrai PRINTF : |%15hhu|\n", (unsigned char)-100);
	ft_printf("06) Mon PRINTF  : |%15hhu|\n", (unsigned char)-100);
	printf("07) Vrai PRINTF : |%.15hhu|\n", (unsigned char)-100);
	ft_printf("07) Mon PRINTF  : |%.15hhu|\n", (unsigned char)-100);
	printf("08) Vrai PRINTF : |%10.5hhu|\n", (unsigned char)52);
	ft_printf("08) Mon PRINTF  : |%10.5hhu|\n", (unsigned char)52);
	printf("09) Vrai PRINTF : |%5.10hhu|\n", (unsigned char)52);
	ft_printf("09) Mon PRINTF  : |%5.10hhu|\n", (unsigned char)52);
	printf("10) Vrai PRINTF : |%20.15hhu|\n", (unsigned char)-100);
	ft_printf("10) Mon PRINTF  : |%20.15hhu|\n", (unsigned char)-100);
	printf("11) Vrai PRINTF : |%15.20hhu|\n", (unsigned char)-100);
	ft_printf("11) Mon PRINTF  : |%15.20hhu|\n", (unsigned char)-100);
	printf("12) Vrai PRINTF : |%-10hhu|\n", (unsigned char)144);
	ft_printf("12) Mon PRINTF  : |%-10hhu|\n", (unsigned char)144);
	printf("13) Vrai PRINTF : |%-.10hhu|\n", (unsigned char)144);
	ft_printf("13) Mon PRINTF  : |%-.10hhu|\n", (unsigned char)144);
	printf("14) Vrai PRINTF : |%-20hhu|\n", (unsigned char)-20);
	ft_printf("14) Mon PRINTF  : |%-20hhu|\n", (unsigned char)-20);
	printf("15) Vrai PRINTF : |%08hhu|\n", (unsigned char)64);
	ft_printf("15) Mon PRINTF  : |%08hhu|\n", (unsigned char)64);
	printf("16) Vrai PRINTF : |%03.4hhu|\n", (unsigned char)10);
	ft_printf("16) Mon PRINTF  : |%03.4hhu|\n", (unsigned char)10);                                                          
	printf("17) Vrai PRINTF : |%.hhu|\n", (unsigned char)0);
	ft_printf("17) Mon PRINTF  : |%.hhu|\n", (unsigned char)0);
	printf("18) Vrai PRINTF : |%.hhu|\n", (unsigned char)88);
	ft_printf("18) Mon PRINTF  : |%.hhu|\n", (unsigned char)88);
	printf("19) Vrai PRINTF : |%hhu|\n", (unsigned char)127);
	ft_printf("19) Mon PRINTF  : |%hhu|\n", (unsigned char)127);
	printf("20) Vrai PRINTF : |%hhu| |%hhu|\n", (unsigned char)-1, (unsigned char)128);
	ft_printf("20) Mon PRINTF  : |%hhu| |%hhu|\n", (unsigned char)-1, (unsigned char)128);
	printf("21) Vrai PRINTF : |%hhu| |%hhu| |%hhu| |%hhu| |%hhu| |%hhu|\n", (unsigned char)42, (unsigned char)100, (unsigned char)25, (unsigned char)16, (unsigned char)30, (unsigned char)69);
	ft_printf("21) Mon PRINTF  : |%hhu| |%hhu| |%hhu| |%hhu| |%hhu| |%hhu|\n", (unsigned char)42, (unsigned char)100, (unsigned char)25, (unsigned char)16, (unsigned char)30, (unsigned char)69);
	printf("22) Vrai PRINTF : |%10hhu| |%-10hhu| |%.5hhu| |%-.5hhu| |%-hhu|\n", (unsigned char)42, (unsigned char)100, (unsigned char)25, (unsigned char)16, (unsigned char)30);
	ft_printf("22) Mon PRINTF  : |%10hhu| |%-10hhu| |%.5hhu| |%-.5hhu| |%-hhu|\n", (unsigned char)42, (unsigned char)100, (unsigned char)25, (unsigned char)16, (unsigned char)30);
	printf("23) Vrai PRINTF : |%hhu| |%hhu| |%hhu| |%hhu| |%hhu| |%hhu|\n", (unsigned char)-42, (unsigned char)-100, (unsigned char)-25, (unsigned char)-16, (unsigned char)-30, (unsigned char)-69);
	ft_printf("23) Mon PRINTF  : |%hhu| |%hhu| |%hhu| |%hhu| |%hhu| |%hhu|\n", (unsigned char)-42, (unsigned char)-100, (unsigned char)-25, (unsigned char)-16, (unsigned char)-30, (unsigned char)-69);
	printf("24) Vrai PRINTF : |%10hhu| |%-10hhu| |%.5hhu| |%-.5hhu| |%-hhu|\n", (unsigned char)-42, (unsigned char)-100, (unsigned char)-25, (unsigned char)-16, (unsigned char)-30);
	ft_printf("24) Mon PRINTF  : |%10hhu| |%-10hhu| |%.5hhu| |%-.5hhu| |%-hu|\n", (unsigned char)-42, (unsigned char)-100, (unsigned char)-25, (unsigned char)-16, (unsigned char)-30);
	ft_printf("--------------------%%lu--------------------\n");
	printf("01) Vrai PRINTF : |%lu|\n",(unsigned long)34);
	ft_printf("01) Mon PRINTF  : |%lu|\n", (unsigned long)34);
	printf("02) Vrai PRINTF : |%lu|\n", (unsigned long)-34);
	ft_printf("02) Mon PRINTF  : |%lu|\n", (unsigned long)-34);
	printf("03) Vrai PRINTF : |%-lu|\n", (unsigned long)50);
	ft_printf("03) Mon PRINTF  : |%-lu|\n", (unsigned long)50);
	printf("04) Vrai PRINTF : |%10lu|\n", (unsigned long)90);
	ft_printf("04) Mon PRINTF  : |%10lu|\n", (unsigned long)90);
	printf("05) Vrai PRINTF : |%.10lu|\n", (unsigned long)90);
	ft_printf("05) Mon PRINTF  : |%.10lu|\n", (unsigned long)90);
	printf("06) Vrai PRINTF : |%15lu|\n", (unsigned long)-100);
	ft_printf("06) Mon PRINTF  : |%15lu|\n", (unsigned long)-100);
	printf("07) Vrai PRINTF : |%.15lu|\n", (unsigned long)-100);
	ft_printf("07) Mon PRINTF  : |%.15lu|\n", (unsigned long)-100);
	printf("08) Vrai PRINTF : |%10.5lu|\n", (unsigned long)52);
	ft_printf("08) Mon PRINTF  : |%10.5lu|\n", (unsigned long)52);
	printf("09) Vrai PRINTF : |%5.10lu|\n", (unsigned long)52);
	ft_printf("09) Mon PRINTF  : |%5.10lu|\n", (unsigned long)52);
	printf("10) Vrai PRINTF : |%20.15lu|\n", (unsigned long)-100000);
	ft_printf("10) Mon PRINTF  : |%20.15lu|\n", (unsigned long)-100000);
	printf("11) Vrai PRINTF : |%15.20lu|\n", (unsigned long)-100000);
	ft_printf("11) Mon PRINTF  : |%15.20lu|\n", (unsigned long)-100000);
	printf("12) Vrai PRINTF : |%-10lu|\n", (unsigned long)144);
	ft_printf("12) Mon PRINTF  : |%-10lu|\n", (unsigned long)144);
	printf("13) Vrai PRINTF : |%-.10lu|\n", (unsigned long)144);
	ft_printf("13) Mon PRINTF  : |%-.10lu|\n", (unsigned long)144);
	printf("14) Vrai PRINTF : |%-20lu|\n", (unsigned long)-20000000);
	ft_printf("14) Mon PRINTF  : |%-20lu|\n", (unsigned long)-20000000);
	printf("15) Vrai PRINTF : |%08lu|\n", (unsigned long)64);
	ft_printf("15) Mon PRINTF  : |%08lu|\n", (unsigned long)64);
	printf("16) Vrai PRINTF : |%03.4lu|\n", (unsigned long)10);
	ft_printf("16) Mon PRINTF  : |%03.4lu|\n", (unsigned long)10);
	printf("17) Vrai PRINTF : |%.lu|\n", (unsigned long)0);
	ft_printf("17) Mon PRINTF  : |%.lu|\n", (unsigned long)0);
	printf("18) Vrai PRINTF : |%.lu|\n", (unsigned long)88);
	ft_printf("18) Mon PRINTF  : |%.lu|\n", (unsigned long)88);
	printf("19) Vrai PRINTF : |%lu|\n", (unsigned long)ULONG_MAX);
	ft_printf("19) Mon PRINTF  : |%lu|\n", (unsigned long)ULONG_MAX);
	printf("20) Vrai PRINTF : |%lu| |%lu|\n", (unsigned long)-1, (unsigned long)ULONG_MAX + 1);
	ft_printf("20) Mon PRINTF  : |%lu| |%lu|\n", (unsigned long)-1, (unsigned long)ULONG_MAX + 1);
	printf("21) Vrai PRINTF : |%lu| |%lu| |%lu| |%lu| |%lu| |%lu|\n", (unsigned long)42, (unsigned long)100, (unsigned long)25, (unsigned long)16, (unsigned long)30, (unsigned long)69);
	ft_printf("21) Mon PRINTF  : |%lu| |%lu| |%lu| |%lu| |%lu| |%lu|\n", (unsigned long)42, (unsigned long)100, (unsigned long)25, (unsigned long)16, (unsigned long)30, (unsigned long)69);
	printf("22) Vrai PRINTF : |%10lu| |%-10lu| |%.5lu| |%-.5lu| |%-lu|\n", (unsigned long)42, (unsigned long)100, (unsigned long)25, (unsigned long)16, (unsigned long)30);
	ft_printf("22) Mon PRINTF  : |%10lu| |%-10lu| |%.5lu| |%-.5lu| |%-lu|\n", (unsigned long)42, (unsigned long)100, (unsigned long)25, (unsigned long)16, (unsigned long)30);
	printf("23) Vrai PRINTF : |%lu| |%lu| |%lu| |%lu| |%lu| |%lu|\n", (unsigned long)-42, (unsigned long)-100, (unsigned long)-25, (unsigned long)-16, (unsigned long)-30, (unsigned long)-69);
	ft_printf("23) Mon PRINTF  : |%lu| |%lu| |%lu| |%lu| |%lu| |%lu|\n", (unsigned long)-42, (unsigned long)-100, (unsigned long)-25, (unsigned long)-16, (unsigned long)-30, (unsigned long)-69);
	printf("24) Vrai PRINTF : |%10lu| |%-10lu| |%.5lu| |%-.5lu| |%-lu|\n", (unsigned long)-42, (unsigned long)-100, (unsigned long)-25, (unsigned long)-16, (unsigned long)-30);
	ft_printf("24) Mon PRINTF  : |%10lu| |%-10lu| |%.5lu| |%-.5lu| |%-lu|\n", (unsigned long)-42, (unsigned long)-100, (unsigned long)-25, (unsigned long)-16, (unsigned long)-30);
	ft_printf("--------------------%%llu--------------------\n");
	printf("01) Vrai PRINTF : |%llu|\n",(unsigned long long)34);
	ft_printf("01) Mon PRINTF  : |%llu|\n", (unsigned long long)34);
	printf("02) Vrai PRINTF : |%llu|\n", (unsigned long long)-34);
	ft_printf("02) Mon PRINTF  : |%llu|\n", (unsigned long long)-34);
	printf("03) Vrai PRINTF : |%-llu|\n", (unsigned long long)50);
	ft_printf("03) Mon PRINTF  : |%-llu|\n", (unsigned long long)50);
	printf("04) Vrai PRINTF : |%10llu|\n", (unsigned long long)90);
	ft_printf("04) Mon PRINTF  : |%10llu|\n", (unsigned long long)90);
	printf("05) Vrai PRINTF : |%.10llu|\n", (unsigned long long)90);
	ft_printf("05) Mon PRINTF  : |%.10llu|\n", (unsigned long long)90);
	printf("06) Vrai PRINTF : |%15llu|\n", (unsigned long long)-100);
	ft_printf("06) Mon PRINTF  : |%15llu|\n", (unsigned long long)-100);
	printf("07) Vrai PRINTF : |%.15llu|\n", (unsigned long long)-100);
	ft_printf("07) Mon PRINTF  : |%.15llu|\n", (unsigned long long)-100);
	printf("08) Vrai PRINTF : |%10.5llu|\n", (unsigned long long)52);
	ft_printf("08) Mon PRINTF  : |%10.5llu|\n", (unsigned long long)52);
	printf("09) Vrai PRINTF : |%5.10llu|\n", (unsigned long long)52);
	ft_printf("09) Mon PRINTF  : |%5.10llu|\n", (unsigned long long)52);
	printf("10) Vrai PRINTF : |%20.15llu|\n", (unsigned long long)-100000);
	ft_printf("10) Mon PRINTF  : |%20.15llu|\n", (unsigned long long)-100000);
	printf("11) Vrai PRINTF : |%15.20llu|\n", (unsigned long long)-100000);
	ft_printf("11) Mon PRINTF  : |%15.20llu|\n", (unsigned long long)-100000);
	printf("12) Vrai PRINTF : |%-10llu|\n", (unsigned long long)144);
	ft_printf("12) Mon PRINTF  : |%-10llu|\n", (unsigned long long)144);
	printf("13) Vrai PRINTF : |%-.10llu|\n", (unsigned long long)144);
	ft_printf("13) Mon PRINTF  : |%-.10llu|\n", (unsigned long long)144);
	printf("14) Vrai PRINTF : |%-20llu|\n", (unsigned long long)-20000000);
	ft_printf("14) Mon PRINTF  : |%-20llu|\n", (unsigned long long)-20000000);
	printf("15) Vrai PRINTF : |%08llu|\n", (unsigned long long)64);
	ft_printf("15) Mon PRINTF  : |%08llu|\n", (unsigned long long)64);
	printf("16) Vrai PRINTF : |%03.4llu|\n", (unsigned long long)10);
	ft_printf("16) Mon PRINTF  : |%03.4llu|\n", (unsigned long long)10);
	printf("17) Vrai PRINTF : |%.llu|\n", (unsigned long long)0);
	ft_printf("17) Mon PRINTF  : |%.llu|\n", (unsigned long long)0);
	printf("18) Vrai PRINTF : |%.llu|\n", (unsigned long long)88);
	ft_printf("18) Mon PRINTF  : |%.llu|\n", (unsigned long long)88);
	printf("19) Vrai PRINTF : |%llu|\n", (unsigned long long)ULLONG_MAX);
	ft_printf("19) Mon PRINTF  : |%llu|\n", (unsigned long long)ULLONG_MAX);
	printf("20) Vrai PRINTF : |%llu| |%llu|\n", (unsigned long long)-1, (unsigned long long)ULLONG_MAX + 1);
	ft_printf("20) Mon PRINTF  : |%llu| |%llu|\n", (unsigned long long)-1, (unsigned long long)ULLONG_MAX + 1);
	printf("21) Vrai PRINTF : |%llu| |%llu| |%llu| |%llu| |%llu| |%llu|\n", (unsigned long long)42, (unsigned long long)100, (unsigned long long)25, (unsigned long long)16, (unsigned long long)30, (unsigned long long)69);
	ft_printf("21) Mon PRINTF  : |%llu| |%llu| |%llu| |%llu| |%llu| |%llu|\n", (unsigned long long)42, (unsigned long long)100, (unsigned long long)25, (unsigned long long)16, (unsigned long long)30, (unsigned long long)69);
	printf("22) Vrai PRINTF : |%10llu| |%-10llu| |%.5llu| |%-.5llu| |%-llu|\n",(unsigned long long)42, (unsigned long long)100, (unsigned long long)25, (unsigned long long)16, (unsigned long long)30);
	ft_printf("22) Mon PRINTF  : |%10llu| |%-10llu| |%.5llu| |%-.5llu| |%-llu|\n", (unsigned long long)42, (unsigned long long)100, (unsigned long long)25, (unsigned long long)16, (unsigned long long)30);
	printf("23) Vrai PRINTF : |%llu| |%llu| |%llu| |%llu| |%llu| |%llu|\n", (unsigned long long)-42, (unsigned long long)-100, (unsigned long long)-25, (unsigned long long)-16, (unsigned long long)-30, (unsigned long long)-69);
	ft_printf("23) Mon PRINTF  : |%llu| |%llu| |%llu| |%llu| |%llu| |%llu|\n", (unsigned long long)-42, (unsigned long long)-100, (unsigned long long)-25, (unsigned long long)-16, (unsigned long long)-30, (unsigned long long)-69);
	printf("24) Vrai PRINTF : |%10llu| |%-10llu| |%.5llu| |%-.5llu| |%-llu|\n", (unsigned long long)-42, (unsigned long long)-100, (unsigned long long)-25, (unsigned long long)-16, (unsigned long long)-30);
	ft_printf("24) Mon PRINTF  : |%10llu| |%-10llu| |%.5llu| |%-.5llu| |%-llu|\n", (unsigned long long)-42, (unsigned long long)-100, (unsigned long long)-25, (unsigned long long)-16, (unsigned long long)-30);
	return (0);
}
