#include <stdio.h>
#include "srcs/ft_printf.h"

int		main(void)
{
	ft_printf("--------------------%%o--------------------\n");
	printf("01) Vrai PRINTF : |%o|\n", 34);
	ft_printf("01) Mon PRINTF  : |%o|\n", 34);
	printf("02) Vrai PRINTF : |%o|\n", -34);
	ft_printf("02) Mon PRINTF  : |%o|\n", -34);
	printf("03) Vrai PRINTF : |%-o|\n", 50);
	ft_printf("03) Mon PRINTF  : |%-o|\n", 50);
	printf("04) Vrai PRINTF : |%10o|\n", 90);
	ft_printf("04) Mon PRINTF  : |%10o|\n", 90);
	printf("05) Vrai PRINTF : |%.10o|\n", 90);
	ft_printf("05) Mon PRINTF  : |%.10o|\n", 90);
	printf("06) Vrai PRINTF : |%15o|\n", -100);
	ft_printf("06) Mon PRINTF  : |%15o|\n", -100);
	printf("07) Vrai PRINTF : |%.15o|\n", -100);
	ft_printf("07) Mon PRINTF  : |%.15o|\n", -100);
	printf("08) Vrai PRINTF : |%10.5o|\n", 52);
	ft_printf("08) Mon PRINTF  : |%10.5o|\n", 52);
	printf("09) Vrai PRINTF : |%5.10o|\n", 52);
	ft_printf("09) Mon PRINTF  : |%5.10o|\n", 52);
	printf("10) Vrai PRINTF : |%20.15o|\n", -100000);
	ft_printf("10) Mon PRINTF  : |%20.15o|\n", -100000);
	printf("11) Vrai PRINTF : |%15.20o|\n", -100000);
	ft_printf("11) Mon PRINTF  : |%15.20o|\n", -100000);
	printf("12) Vrai PRINTF : |%-10o|\n", 144);
	ft_printf("12) Mon PRINTF  : |%-10o|\n", 144);
	printf("13) Vrai PRINTF : |%-.10o|\n", 144);
	ft_printf("13) Mon PRINTF  : |%-.10o|\n", 144);
	printf("14) Vrai PRINTF : |%-20o|\n", -20000000);
	ft_printf("14) Mon PRINTF  : |%-20o|\n", -20000000);
	printf("15) Vrai PRINTF : |%08o|\n", 64);
	ft_printf("15) Mon PRINTF  : |%08o|\n", 64);
	printf("16) Vrai PRINTF : |%03.4o|\n", 10);
	ft_printf("16) Mon PRINTF  : |%03.4o|\n", 10);
	printf("17) Vrai PRINTF : |%#o|\n", 34);
	ft_printf("17) Mon PRINTF  : |%#o|\n", 34);
	printf("18) Vrai PRINTF : |%#.5o|\n", 34);
	ft_printf("18) Mon PRINTF  : |%#.5o|\n", 34);
	printf("19) Vrai PRINTF : |%#5o|\n", 86);
	ft_printf("19) Mon PRINTF  : |%#5o|\n", 86);
	printf("20) Vrai PRINTF : |%#10.5o|\n", 70);
	ft_printf("20) Mon PRINTF  : |%#10.5o|\n", 70);
	printf("21) Vrai PRINTF : |%#o|\n", 0);
	ft_printf("21) Mon PRINTF  : |%#o|\n", 0);
	printf("22) Vrai PRINTF : |%#.o|\n", 0);
	ft_printf("22) Mon PRINTF  : |%#.o|\n", 0);
	printf("23) Vrai PRINTF : |%.o|\n", 0);
	ft_printf("23) Mon PRINTF  : |%.o|\n", 0);
	printf("24) Vrai PRINTF : |%.o|\n", 88);
	ft_printf("24) Mon PRINTF  : |%.o|\n", 88);
	printf("25) Vrai PRINTF : |%#.o|\n", 88);
	ft_printf("25) Mon PRINTF  : |%#.o|\n", 88);
	printf("26) Vrai PRINTF : |%o|\n", UINT_MAX);
	ft_printf("26) Mon PRINTF  : |%o|\n", UINT_MAX);
	printf("27) Vrai PRINTF : |%#o|\n", UINT_MAX);
	ft_printf("27) Mon PRINTF  : |%#o|\n", UINT_MAX);
	printf("28) Vrai PRINTF : |%#o| |%#o|\n", (unsigned int)-1, UINT_MAX + 1);
	ft_printf("28) Mon PRINTF  : |%#o| |%#o|\n", (unsigned int)-1, UINT_MAX + 1);
	printf("29) Vrai PRINTF : |%o| |%o|\n", (unsigned int)-1, UINT_MAX + 1);
	ft_printf("29) Mon PRINTF  : |%o| |%o|\n", (unsigned int)-1, UINT_MAX + 1);
	printf("30) Vrai PRINTF : |%o| |%o| |%o| |%o| |%o| |%o|\n", 42, 100, 25, 16, 30, 69);
	ft_printf("30) Mon PRINTF  : |%o| |%o| |%o| |%o| |%o| |%o|\n", 42, 100, 25, 16, 30, 69);
	printf("31) Vrai PRINTF : |%10o| |%-10o| |%.5o| |%-.5o| |%-o|\n", 42, 100, 25, 16, 30);
	ft_printf("31) Mon PRINTF  : |%10o| |%-10o| |%.5o| |%-.5o| |%-o|\n", 42, 100, 25, 16, 30);
	printf("32) Vrai PRINTF : |%o| |%o| |%o| |%o| |%o| |%o|\n", -42, -100, -25, -16, -30, -69);
	ft_printf("32) Mon PRINTF  : |%o| |%o| |%o| |%o| |%o| |%o|\n", -42, -100, -25, -16, -30, -69);
	printf("33) Vrai PRINTF : |%10o| |%-10o| |%.5o| |%-.5o| |%-o|\n", -42, -100, -25, -16, -30);
	ft_printf("33) Mon PRINTF  : |%10o| |%-10o| |%.5o| |%-.5o| |%-o|\n", -42, -100, -25, -16, -30);
	ft_printf("--------------------%%ho--------------------\n");
	printf("01) Vrai PRINTF : |%ho|\n", (unsigned short)34);
	ft_printf("01) Mon PRINTF  : |%ho|\n", (unsigned short)34);
	printf("02) Vrai PRINTF : |%ho|\n", (unsigned short)-34);
	ft_printf("02) Mon PRINTF  : |%ho|\n", (unsigned short)-34);
	printf("03) Vrai PRINTF : |%-ho|\n", (unsigned short)50);
	ft_printf("03) Mon PRINTF  : |%-ho|\n", (unsigned short)50);
	printf("04) Vrai PRINTF : |%10ho|\n", (unsigned short)90);
	ft_printf("04) Mon PRINTF  : |%10ho|\n", (unsigned short)90);
	printf("05) Vrai PRINTF : |%.10ho|\n", (unsigned short)90);
	ft_printf("05) Mon PRINTF  : |%.10ho|\n", (unsigned short)90);
	printf("06) Vrai PRINTF : |%15ho|\n", (unsigned short)-100);
	ft_printf("06) Mon PRINTF  : |%15ho|\n", (unsigned short)-100);
	printf("07) Vrai PRINTF : |%.15ho|\n", (unsigned short)-100);
	ft_printf("07) Mon PRINTF  : |%.15ho|\n", (unsigned short)-100);
	printf("08) Vrai PRINTF : |%10.5ho|\n", (unsigned short)52);
	ft_printf("08) Mon PRINTF  : |%10.5ho|\n", (unsigned short)52);
	printf("09) Vrai PRINTF : |%5.10ho|\n", (unsigned short)52);
	ft_printf("09) Mon PRINTF  : |%5.10ho|\n", (unsigned short)52);
	printf("10) Vrai PRINTF : |%20.15ho|\n", (unsigned short)-10000);
	ft_printf("10) Mon PRINTF  : |%20.15ho|\n", (unsigned short)-10000);
	printf("11) Vrai PRINTF : |%15.20ho|\n", (unsigned short)-10000);
	ft_printf("11) Mon PRINTF  : |%15.20ho|\n", (unsigned short)-10000);
	printf("12) Vrai PRINTF : |%-10ho|\n", (unsigned short)144);
	ft_printf("12) Mon PRINTF  : |%-10ho|\n", (unsigned short)144);
	printf("13) Vrai PRINTF : |%-.10ho|\n", (unsigned short)144);
	ft_printf("13) Mon PRINTF  : |%-.10ho|\n", (unsigned short)144);
	printf("14) Vrai PRINTF : |%-20ho|\n", (unsigned short)-20000);
	ft_printf("14) Mon PRINTF  : |%-20ho|\n", (unsigned short)-20000);
	printf("15) Vrai PRINTF : |%08ho|\n", (unsigned short)64);
	ft_printf("15) Mon PRINTF  : |%08ho|\n", (unsigned short)64);
	printf("16) Vrai PRINTF : |%03.4ho|\n", (unsigned short)10);
	ft_printf("16) Mon PRINTF  : |%03.4ho|\n", (unsigned short)10);
	printf("17) Vrai PRINTF : |%#ho|\n", (unsigned short)34);
	ft_printf("17) Mon PRINTF  : |%#ho|\n", (unsigned short)34);
	printf("18) Vrai PRINTF : |%#.5ho|\n", (unsigned short)34);
	ft_printf("18) Mon PRINTF  : |%#.5ho|\n", (unsigned short)34);
	printf("19) Vrai PRINTF : |%#5ho|\n", (unsigned short)86);
	ft_printf("19) Mon PRINTF  : |%#5ho|\n", (unsigned short)86);
	printf("20) Vrai PRINTF : |%#10.5ho|\n", (unsigned short)70);
	ft_printf("20) Mon PRINTF  : |%#10.5ho|\n", (unsigned short)70);
	printf("21) Vrai PRINTF : |%#ho|\n", (unsigned short)0);
	ft_printf("21) Mon PRINTF  : |%#ho|\n", (unsigned short)0);
	printf("22) Vrai PRINTF : |%#.ho|\n", (unsigned short)0);
	ft_printf("22) Mon PRINTF  : |%#.ho|\n", (unsigned short)0);
	printf("23) Vrai PRINTF : |%.ho|\n", (unsigned short)0);
	ft_printf("23) Mon PRINTF  : |%.ho|\n", (unsigned short)0);
	printf("24) Vrai PRINTF : |%.ho|\n", (unsigned short)88);
	ft_printf("24) Mon PRINTF  : |%.ho|\n", (unsigned short)88);
	printf("25) Vrai PRINTF : |%#.ho|\n", (unsigned short)88);
	ft_printf("25) Mon PRINTF  : |%#.ho|\n", (unsigned short)88);
	printf("26) Vrai PRINTF : |%ho|\n", (unsigned short)USHRT_MAX);
	ft_printf("26) Mon PRINTF  : |%ho|\n", (unsigned short)USHRT_MAX);
	printf("27) Vrai PRINTF : |%#ho|\n", (unsigned short)USHRT_MAX);
	ft_printf("27) Mon PRINTF  : |%#ho|\n", (unsigned short)USHRT_MAX);
	printf("28) Vrai PRINTF : |%#ho| |%#ho|\n", (unsigned short)-1, (unsigned short)65536);
	ft_printf("28) Mon PRINTF  : |%#ho| |%#ho|\n", (unsigned short)-1, (unsigned short)65536);
	printf("29) Vrai PRINTF : |%ho| |%ho|\n", (unsigned short)-1, (unsigned short)65536);
	ft_printf("29) Mon PRINTF  : |%ho| |%ho|\n", (unsigned short)-1, (unsigned short)65536);
	printf("30) Vrai PRINTF : |%ho| |%ho| |%ho| |%ho| |%ho| |%ho|\n", (unsigned short)42, (unsigned short)100, (unsigned short)25, (unsigned short)16, (unsigned short)30, (unsigned short)69);
	ft_printf("30) Mon PRINTF  : |%ho| |%ho| |%ho| |%ho| |%ho| |%ho|\n", (unsigned short)42, (unsigned short)100, (unsigned short)25, (unsigned short)16, (unsigned short)30, (unsigned short)69);
	printf("31) Vrai PRINTF : |%10ho| |%-10ho| |%.5ho| |%-.5ho| |%-ho|\n", (unsigned short)42, (unsigned short)100, (unsigned short)25, (unsigned short)16, (unsigned short)30);
	ft_printf("31) Mon PRINTF  : |%10ho| |%-10ho| |%.5ho| |%-.5ho| |%-ho|\n", (unsigned short)42, (unsigned short)100, (unsigned short)25, (unsigned short)16, (unsigned short)30);
	printf("32) Vrai PRINTF : |%ho| |%ho| |%ho| |%ho| |%ho| |%ho|\n", (unsigned short)-42, (unsigned short)-100, (unsigned short)-25, (unsigned short)-16, (unsigned short)-30, (unsigned short)-69);
	ft_printf("32) Mon PRINTF  : |%ho| |%ho| |%ho| |%ho| |%ho| |%ho|\n", (unsigned short)-42, (unsigned short)-100, (unsigned short)-25, (unsigned short)-16, (unsigned short)-30, (unsigned short)-69);
	printf("33) Vrai PRINTF : |%10ho| |%-10ho| |%.5ho| |%-.5ho| |%-ho|\n", (unsigned short)-42, (unsigned short)-100, (unsigned short)-25, (unsigned short)-16, (unsigned short)-30);
	ft_printf("33) Mon PRINTF  : |%10ho| |%-10ho| |%.5ho| |%-.5ho| |%-ho|\n", (unsigned short)-42, (unsigned short)-100, (unsigned short)-25, (unsigned short)-16, (unsigned short)-30);
	ft_printf("--------------------%%hho--------------------\n");
	printf("01) Vrai PRINTF : |%hho|\n", (unsigned char)34);
	ft_printf("01) Mon PRINTF  : |%hho|\n", (unsigned char)34);
	printf("02) Vrai PRINTF : |%hho|\n", (unsigned char)-34);
	ft_printf("02) Mon PRINTF  : |%hho|\n", (unsigned char)-34);
	printf("03) Vrai PRINTF : |%-hho|\n", (unsigned char)50);
	ft_printf("03) Mon PRINTF  : |%-hho|\n", (unsigned char)50);
	printf("04) Vrai PRINTF : |%10hho|\n", (unsigned char)90);
	ft_printf("04) Mon PRINTF  : |%10hho|\n", (unsigned char)90);
	printf("05) Vrai PRINTF : |%.10hho|\n", (unsigned char)90);
	ft_printf("05) Mon PRINTF  : |%.10hho|\n", (unsigned char)90);
	printf("06) Vrai PRINTF : |%15hho|\n", (unsigned char)-100);
	ft_printf("06) Mon PRINTF  : |%15hho|\n", (unsigned char)-100);
	printf("07) Vrai PRINTF : |%.15hho|\n", (unsigned char)-100);
	ft_printf("07) Mon PRINTF  : |%.15hho|\n", (unsigned char)-100);
	printf("08) Vrai PRINTF : |%10.5hho|\n", (unsigned char)52);
	ft_printf("08) Mon PRINTF  : |%10.5hho|\n", (unsigned char)52);
	printf("09) Vrai PRINTF : |%5.10hho|\n", (unsigned char)52);
	ft_printf("09) Mon PRINTF  : |%5.10hho|\n", (unsigned char)52);
	printf("10) Vrai PRINTF : |%20.15hho|\n", (unsigned char)-10000);
	ft_printf("10) Mon PRINTF  : |%20.15hho|\n", (unsigned char)-10000);
	printf("11) Vrai PRINTF : |%15.20hho|\n", (unsigned char)-10000);
	ft_printf("11) Mon PRINTF  : |%15.20hho|\n", (unsigned char)-10000);
	printf("12) Vrai PRINTF : |%-10hho|\n", (unsigned char)144);
	ft_printf("12) Mon PRINTF  : |%-10hho|\n", (unsigned char)144);
	printf("13) Vrai PRINTF : |%-.10hho|\n", (unsigned char)144);
	ft_printf("13) Mon PRINTF  : |%-.10hho|\n", (unsigned char)144);
	printf("14) Vrai PRINTF : |%-20hho|\n", (unsigned char)-20000);
	ft_printf("14) Mon PRINTF  : |%-20hho|\n", (unsigned char)-20000);
	printf("15) Vrai PRINTF : |%08hho|\n", (unsigned char)64);
	ft_printf("15) Mon PRINTF  : |%08hho|\n", (unsigned char)64);
	printf("16) Vrai PRINTF : |%03.4hho|\n", (unsigned char)10);
	ft_printf("16) Mon PRINTF  : |%03.4hho|\n", (unsigned char)10);
	printf("17) Vrai PRINTF : |%#hho|\n", (unsigned char)34);
	ft_printf("17) Mon PRINTF  : |%#hho|\n", (unsigned char)34);
	printf("18) Vrai PRINTF : |%#.5hho|\n", (unsigned char)34);
	ft_printf("18) Mon PRINTF  : |%#.5hho|\n", (unsigned char)34);
	printf("19) Vrai PRINTF : |%#5hho|\n", (unsigned char)86);
	ft_printf("19) Mon PRINTF  : |%#5hho|\n", (unsigned char)86);
	printf("20) Vrai PRINTF : |%#10.5hho|\n", (unsigned char)70);
	ft_printf("20) Mon PRINTF  : |%#10.5hho|\n", (unsigned char)70);
	printf("21) Vrai PRINTF : |%#hho|\n", (unsigned char)0);
	ft_printf("21) Mon PRINTF  : |%#hho|\n", (unsigned char)0);
	printf("22) Vrai PRINTF : |%#.hho|\n", (unsigned char)0);
	ft_printf("22) Mon PRINTF  : |%#.hho|\n", (unsigned char)0);
	printf("23) Vrai PRINTF : |%.hho|\n", (unsigned char)0);
	ft_printf("23) Mon PRINTF  : |%.hho|\n", (unsigned char)0);
	printf("24) Vrai PRINTF : |%.hho|\n", (unsigned char)88);
	ft_printf("24) Mon PRINTF  : |%.hho|\n", (unsigned char)88);
	printf("25) Vrai PRINTF : |%#.hho|\n", (unsigned char)88);
	ft_printf("25) Mon PRINTF  : |%#.hho|\n", (unsigned char)88);
	printf("26) Vrai PRINTF : |%hho|\n", (unsigned char)255);
	ft_printf("26) Mon PRINTF  : |%hho|\n", (unsigned char)255);
	printf("27) Vrai PRINTF : |%#hho|\n", (unsigned char)255);
	ft_printf("27) Mon PRINTF  : |%#hho|\n", (unsigned char)255);
	printf("28) Vrai PRINTF : |%#hho| |%#hho|\n", (unsigned char)-1, (unsigned char)256);
	ft_printf("28) Mon PRINTF  : |%#hho| |%#hho|\n", (unsigned char)-1, (unsigned char) 256);
	printf("29) Vrai PRINTF : |%hho| |%hho| |%hho| |%hho| |%hho| |%hho|\n", (unsigned char)42, (unsigned char)100, (unsigned char)25, (unsigned char)16, (unsigned char)30, (unsigned char)69);
	ft_printf("29) Mon PRINTF  : |%hho| |%hho| |%hho| |%hho| |%hho| |%hho|\n", (unsigned char)42, (unsigned char)100, (unsigned char)25, (unsigned char)16, (unsigned char)30, (unsigned char)69);
	printf("30) Vrai PRINTF : |%10hho| |%-10hho| |%.5hho| |%-.5hho| |%-hho|\n", (unsigned char)42, (unsigned char)100, (unsigned char)25, (unsigned char)16, (unsigned char)30);
	ft_printf("30) Mon PRINTF  : |%10hho| |%-10hho| |%.5hho| |%-.5hho| |%-hho|\n", (unsigned char)42, (unsigned char)100, (unsigned char)25, (unsigned char)16, (unsigned char)30);
	printf("31) Vrai PRINTF : |%hho| |%hho| |%hho| |%hho| |%hho| |%hho|\n", (unsigned char)-42, (unsigned char)-100, (unsigned char)-25, (unsigned char)-16, (unsigned char)-30, (unsigned char)-69);
	ft_printf("31) Mon PRINTF  : |%hho| |%hho| |%hho| |%hho| |%hho| |%hho|\n", (unsigned char)-42, (unsigned char)-100, (unsigned char)-25, (unsigned char)-16, (unsigned char)-30, (unsigned char)-69);
	printf("32) Vrai PRINTF : |%10hho| |%-10hho| |%.5hho| |%-.5hho| |%-hho|\n", (unsigned char)-42, (unsigned char)-100, (unsigned char)-25, (unsigned char)-16, (unsigned char)-30);
	ft_printf("32) Mon PRINTF  : |%10hho| |%-10hho| |%.5hho| |%-.5hho| |%-hho|\n", (unsigned char)-42, (unsigned char)-100, (unsigned char)-25, (unsigned char)-16, (unsigned char)-30);
	ft_printf("--------------------%%lo--------------------\n");
	printf("01) Vrai PRINTF : |%lo|\n",(unsigned long)34);
	ft_printf("01) Mon PRINTF  : |%lo|\n", (unsigned long)34);
	printf("02) Vrai PRINTF : |%lo|\n", (unsigned long)-34);
	ft_printf("02) Mon PRINTF  : |%lo|\n", (unsigned long)-34);
	printf("03) Vrai PRINTF : |%-lo|\n", (unsigned long)50);
	ft_printf("03) Mon PRINTF  : |%-lo|\n", (unsigned long)50);
	printf("04) Vrai PRINTF : |%10lo|\n", (unsigned long)90);
	ft_printf("04) Mon PRINTF  : |%10lo|\n", (unsigned long)90);
	printf("05) Vrai PRINTF : |%.10lo|\n", (unsigned long)90);
	ft_printf("05) Mon PRINTF  : |%.10lo|\n", (unsigned long)90);
	printf("06) Vrai PRINTF : |%15lo|\n", (unsigned long)-100);
	ft_printf("06) Mon PRINTF  : |%15lo|\n", (unsigned long)-100);
	printf("07) Vrai PRINTF : |%.15lo|\n", (unsigned long)-100);
	ft_printf("07) Mon PRINTF  : |%.15lo|\n", (unsigned long)-100);
	printf("08) Vrai PRINTF : |%10.5lo|\n", (unsigned long)52);
	ft_printf("08) Mon PRINTF  : |%10.5lo|\n", (unsigned long)52);
	printf("09) Vrai PRINTF : |%5.10lo|\n", (unsigned long)52);
	ft_printf("09) Mon PRINTF  : |%5.10lo|\n", (unsigned long)52);
	printf("10) Vrai PRINTF : |%20.15lo|\n", (unsigned long)-100000);
	ft_printf("10) Mon PRINTF  : |%20.15lo|\n", (unsigned long)-100000);
	printf("11) Vrai PRINTF : |%15.20lo|\n", (unsigned long)-100000);
	ft_printf("11) Mon PRINTF  : |%15.20lo|\n", (unsigned long)-100000);
	printf("12) Vrai PRINTF : |%-10lo|\n", (unsigned long)144);
	ft_printf("12) Mon PRINTF  : |%-10lo|\n", (unsigned long)144);
	printf("13) Vrai PRINTF : |%-.10lo|\n", (unsigned long)144);
	ft_printf("13) Mon PRINTF  : |%-.10lo|\n", (unsigned long)144);
	printf("14) Vrai PRINTF : |%-20lo|\n", (unsigned long)-20000000);
	ft_printf("14) Mon PRINTF  : |%-20lo|\n", (unsigned long)-20000000);
	printf("15) Vrai PRINTF : |%08lo|\n", (unsigned long)64);
	ft_printf("15) Mon PRINTF  : |%08lo|\n", (unsigned long)64);
	printf("16) Vrai PRINTF : |%03.4lo|\n", (unsigned long)10);
	ft_printf("16) Mon PRINTF  : |%03.4lo|\n", (unsigned long)10);
	printf("17) Vrai PRINTF : |%#lo|\n", (unsigned long)34);
	ft_printf("17) Mon PRINTF  : |%#lo|\n", (unsigned long)34);
	printf("18) Vrai PRINTF : |%#.5lo|\n", (unsigned long)34);
	ft_printf("18) Mon PRINTF  : |%#.5lo|\n", (unsigned long)34);
	printf("19) Vrai PRINTF : |%#5lo|\n", (unsigned long)86);
	ft_printf("19) Mon PRINTF  : |%#5lo|\n", (unsigned long)86);
	printf("20) Vrai PRINTF : |%#10.5lo|\n", (unsigned long)70);
	ft_printf("20) Mon PRINTF  : |%#10.5lo|\n", (unsigned long)70);
	printf("21) Vrai PRINTF : |%#lo|\n", (unsigned long)0);
	ft_printf("21) Mon PRINTF  : |%#lo|\n", (unsigned long)0);
	printf("22) Vrai PRINTF : |%#.lo|\n", (unsigned long)0);
	ft_printf("22) Mon PRINTF  : |%#.lo|\n", (unsigned long)0);
	printf("23) Vrai PRINTF : |%.lo|\n", (unsigned long)0);
	ft_printf("23) Mon PRINTF  : |%.lo|\n", (unsigned long)0);
	printf("24) Vrai PRINTF : |%.lo|\n", (unsigned long)88);
	ft_printf("24) Mon PRINTF  : |%.lo|\n", (unsigned long)88);
	printf("25) Vrai PRINTF : |%#.lo|\n", (unsigned long)88);
	ft_printf("25) Mon PRINTF  : |%#.lo|\n", (unsigned long)88);
	printf("26) Vrai PRINTF : |%lo|\n", (unsigned long)UINT_MAX);
	ft_printf("26) Mon PRINTF  : |%lo|\n", (unsigned long)UINT_MAX);
	printf("27) Vrai PRINTF : |%#lo|\n", (unsigned long)-1, ULONG_MAX);
	ft_printf("27) Mon PRINTF  : |%#lo|\n", (unsigned long)-1, ULONG_MAX);
	printf("28) Vrai PRINTF : |%#lo| |%#lo|\n", (unsigned long)-1, ULONG_MAX + 1);
	ft_printf("28) Mon PRINTF  : |%#lo| |%#lo|\n", (unsigned long)-1, ULONG_MAX + 1);
	ft_printf("--------------------%%llo--------------------\n");
	printf("01) Vrai PRINTF : |%llo|\n",(unsigned long long)34);
	ft_printf("01) Mon PRINTF  : |%llo|\n", (unsigned long long)34);
	printf("02) Vrai PRINTF : |%llo|\n", (unsigned long long)-34);
	ft_printf("02) Mon PRINTF  : |%llo|\n", (unsigned long long)-34);
	printf("03) Vrai PRINTF : |%-llo|\n", (unsigned long long)50);
	ft_printf("03) Mon PRINTF  : |%-llo|\n", (unsigned long long)50);
	printf("04) Vrai PRINTF : |%10llo|\n", (unsigned long long)90);
	ft_printf("04) Mon PRINTF  : |%10llo|\n", (unsigned long long)90);
	printf("05) Vrai PRINTF : |%.10llo|\n", (unsigned long long)90);
	ft_printf("05) Mon PRINTF  : |%.10llo|\n", (unsigned long long)90);
	printf("06) Vrai PRINTF : |%15llo|\n", (unsigned long long)-100);
	ft_printf("06) Mon PRINTF  : |%15llo|\n", (unsigned long long)-100);
	printf("07) Vrai PRINTF : |%.15llo|\n", (unsigned long long)-100);
	ft_printf("07) Mon PRINTF  : |%.15llo|\n", (unsigned long long)-100);
	printf("08) Vrai PRINTF : |%10.5llo|\n", (unsigned long long)52);
	ft_printf("08) Mon PRINTF  : |%10.5llo|\n", (unsigned long long)52);
	printf("09) Vrai PRINTF : |%5.10llo|\n", (unsigned long long)52);
	ft_printf("09) Mon PRINTF  : |%5.10llo|\n", (unsigned long long)52);
	printf("10) Vrai PRINTF : |%20.15llo|\n", (unsigned long long)-100000);
	ft_printf("10) Mon PRINTF  : |%20.15llo|\n", (unsigned long long)-100000);
	printf("11) Vrai PRINTF : |%15.20llo|\n", (unsigned long long)-100000);
	ft_printf("11) Mon PRINTF  : |%15.20llo|\n", (unsigned long long)-100000);
	printf("12) Vrai PRINTF : |%-10llo|\n", (unsigned long long)144);
	ft_printf("12) Mon PRINTF  : |%-10llo|\n", (unsigned long long)144);
	printf("13) Vrai PRINTF : |%-.10llo|\n", (unsigned long long)144);
	ft_printf("13) Mon PRINTF  : |%-.10llo|\n", (unsigned long long)144);
	printf("14) Vrai PRINTF : |%-20llo|\n", (unsigned long long)-20000000);
	ft_printf("14) Mon PRINTF  : |%-20llo|\n", (unsigned long long)-20000000);
	printf("15) Vrai PRINTF : |%08llo|\n", (unsigned long long)64);
	ft_printf("15) Mon PRINTF  : |%08llo|\n", (unsigned long long)64);
	printf("16) Vrai PRINTF : |%03.4llo|\n", (unsigned long long)10);
	ft_printf("16) Mon PRINTF  : |%03.4llo|\n", (unsigned long long)10);
	printf("17) Vrai PRINTF : |%#llo|\n", (unsigned long long)34);
	ft_printf("17) Mon PRINTF  : |%#llo|\n", (unsigned long long)34);
	printf("18) Vrai PRINTF : |%#.5llo|\n", (unsigned long long)34);
	ft_printf("18) Mon PRINTF  : |%#.5llo|\n", (unsigned long long)34);
	printf("19) Vrai PRINTF : |%#5llo|\n", (unsigned long long)86);
	ft_printf("19) Mon PRINTF  : |%#5llo|\n", (unsigned long long)86);
	printf("20) Vrai PRINTF : |%#10.5llo|\n", (unsigned long long)70);
	ft_printf("20) Mon PRINTF  : |%#10.5llo|\n", (unsigned long long)70);
	printf("21) Vrai PRINTF : |%#llo|\n", (unsigned long long)0);
	ft_printf("21) Mon PRINTF  : |%#llo|\n", (unsigned long long)0);
	printf("22) Vrai PRINTF : |%#.llo|\n", (unsigned long long)0);
	ft_printf("22) Mon PRINTF  : |%#.llo|\n", (unsigned long long)0);
	printf("23) Vrai PRINTF : |%.llo|\n", (unsigned long long)0);
	ft_printf("23) Mon PRINTF  : |%.llo|\n", (unsigned long long)0);
	printf("24) Vrai PRINTF : |%.llo|\n", (unsigned long long)88);
	ft_printf("24) Mon PRINTF  : |%.llo|\n", (unsigned long long)88);
	printf("25) Vrai PRINTF : |%#.llo|\n", (unsigned long long)88);
	ft_printf("25) Mon PRINTF  : |%#.llo|\n", (unsigned long long)88);
	printf("26) Vrai PRINTF : |%llo|\n", (unsigned long long)ULLONG_MAX);
	ft_printf("26) Mon PRINTF  : |%llo|\n", (unsigned long long)ULLONG_MAX);
	printf("27) Vrai PRINTF : |%#llo|\n", (unsigned long long)-1, ULLONG_MAX);
	ft_printf("27) Mon PRINTF  : |%#llo|\n", (unsigned long long)-1, ULLONG_MAX);
	printf("28) Vrai PRINTF : |%#llo| |%#llo|\n", (unsigned long long)-1, ULLONG_MAX + 1);
	ft_printf("28) Mon PRINTF  : |%#llo| |%#llo|\n", (unsigned long long)-1, ULLONG_MAX + 1);
	return (0);
}
